const CARDS_DATA = {
  A401_Cheetah: {
    type: 'animal',
    name: 'Cheetah',
    latin: 'Acinonyx jubatus - Vulnerable',
    number: 401,
    cost: 17,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 5,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Predator', 'Predator'],
    prerequisites: [],
    continents: ['Africa'],
    ability: { Sprint: 3 },
    soloAbility: { Sprint: 3 },
  },
  A402_Lion: {
    type: 'animal',
    name: 'Lion',
    latin: 'Panthera leo - Vulnerable',
    number: 402,
    cost: 16,
    appeal: 9,
    conservation: 0,
    reputation: 0,
    enclosureSize: 4,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Predator'],
    prerequisites: { Predator: 3 },
    continents: ['Africa'],
    ability: { Pack: null },
    soloAbility: { Pack: null },
  },
  A403_Leopard: {
    type: 'animal',
    name: 'Leopard',
    latin: 'Panthera pardus - Vunerable',
    number: 403,
    cost: 20,
    appeal: 7,
    conservation: 1,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: { Rock: 1 },
    specialEnclosure: [],
    categories: ['Predator'],
    prerequisites: { 'Partner-Zoo': 1 },
    continents: ['Africa'],
    ability: { Hunter: 4 },
    soloAbility: { Hunter: 4 },
  },
  A404_Caracal: {
    type: 'animal',
    name: 'Caracal',
    latin: 'Caracal caracal',
    number: 404,
    cost: 9,
    appeal: 4,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Predator'],
    prerequisites: [],
    continents: ['Africa'],
    ability: { Hunter: 2 },
    soloAbility: { Hunter: 2 },
  },
  A405_FennecFox: {
    type: 'animal',
    name: 'Fennec Fox',
    latin: 'Vulpes zerda',
    number: 405,
    cost: 8,
    appeal: 3,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Predator'],
    prerequisites: [],
    continents: ['Africa'],
    ability: { Clever: null },
    soloAbility: { Clever: null },
  },
  A406_SiberianTiger: {
    type: 'animal',
    name: 'Siberian Tiger',
    latin: 'Panthera tigris altaica - Endangered',
    number: 406,
    cost: 30,
    appeal: 10,
    conservation: 2,
    reputation: 1,
    enclosureSize: 5,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Predator'],
    prerequisites: { Asia: 3 },
    continents: ['Asia'],
    ability: [],
    soloAbility: [],
  },
  A407_SumatranTiger: {
    type: 'animal',
    name: 'Sumatran Tiger',
    latin: 'Panthera tigris sumatrae - Critically Endangered',
    number: 407,
    cost: 26,
    appeal: 8,
    conservation: 2,
    reputation: 1,
    enclosureSize: 4,
    enclosureRequirements: { Water: 2 },
    specialEnclosure: [],
    categories: ['Predator'],
    prerequisites: { Science: 2 },
    continents: ['Asia'],
    ability: [],
    soloAbility: [],
  },
  A408_SlothBear: {
    type: 'animal',
    name: 'Sloth Bear',
    latin: 'Melursus ursinus - Vulnerable',
    number: 408,
    cost: 14,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Predator', 'Bear'],
    prerequisites: [],
    continents: ['Asia'],
    ability: { Boost: 'Association' },
    soloAbility: { Boost: 'Association' },
  },
  A409_SunBear: {
    type: 'animal',
    name: 'Sun Bear',
    latin: 'Helarctos malayanus - Vulnerable',
    number: 409,
    cost: 16,
    appeal: 5,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Predator', 'Bear'],
    prerequisites: { 'Partner-Zoo': 1 },
    continents: ['Asia'],
    ability: { Action: 'Association' },
    soloAbility: { Action: 'Association' },
  },
  A410_YellowthroatedMarten: {
    type: 'animal',
    name: 'Yellow-throated Marten',
    latin: 'Martes flavigula',
    number: 410,
    cost: 7,
    appeal: 3,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Predator'],
    prerequisites: [],
    continents: ['Asia'],
    ability: { Hunter: 1 },
    soloAbility: { Hunter: 1 },
  },
  A411_GrizzlyBear: {
    type: 'animal',
    name: 'Grizzly Bear',
    latin: 'Ursus arctos horribilis',
    number: 411,
    cost: 22,
    appeal: 9,
    conservation: 0,
    reputation: 0,
    enclosureSize: 5,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Predator', 'Bear'],
    prerequisites: { Predator: 2, AnimalsII: 1 },
    continents: ['Americas'],
    ability: { Inventive: 0, FullThroated: null },
    soloAbility: { Inventive: 0, FullThroated: null },
  },
  A412_Jaguar: {
    type: 'animal',
    name: 'Jaguar',
    latin: 'Panthera onca - Near Threatened',
    number: 412,
    cost: 16,
    appeal: 8,
    conservation: 0,
    reputation: 0,
    enclosureSize: 4,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Predator'],
    prerequisites: { Americas: 1 },
    continents: ['Americas'],
    ability: { Hunter: 4 },
    soloAbility: { Hunter: 4 },
  },
  A413_Cougar: {
    type: 'animal',
    name: 'Cougar',
    latin: 'Puma concolor',
    number: 413,
    cost: 10,
    appeal: 5,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: { Rock: 1 },
    specialEnclosure: [],
    categories: ['Predator'],
    prerequisites: [],
    continents: ['Americas'],
    ability: { Jumping: 3 },
    soloAbility: { Jumping: 3 },
  },
  A414_SouthAmericanCoati: {
    type: 'animal',
    name: 'South American Coati',
    latin: 'Nasua nasua',
    number: 414,
    cost: 11,
    appeal: 4,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: { Rock: 1 },
    specialEnclosure: [],
    categories: ['Predator', 'Bear'],
    prerequisites: [],
    continents: ['Americas'],
    ability: { Inventive: 1 },
    soloAbility: { Inventive: 1 },
  },
  A415_Raccoon: {
    type: 'animal',
    name: 'Raccoon',
    latin: 'Procyon lotor',
    number: 415,
    cost: 11,
    appeal: 4,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Predator', 'Bear'],
    prerequisites: [],
    continents: ['Americas'],
    ability: { Boost: 'Association' },
    soloAbility: { Boost: 'Association' },
  },
  A416_EurasianBrownBear: {
    type: 'animal',
    name: 'Eurasian Brown Bear',
    latin: 'Ursus arctos arctos',
    number: 416,
    cost: 20,
    appeal: 8,
    conservation: 0,
    reputation: 0,
    enclosureSize: 5,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: [],
    categories: ['Predator', 'Bear'],
    prerequisites: { Bear: 1, AnimalsII: 1 },
    continents: ['Europe'],
    ability: { Multiplier: 'Association', FullThroated: null },
    soloAbility: { Multiplier: 'Association', FullThroated: null },
  },
  A417_Wolf: {
    type: 'animal',
    name: 'Wolf',
    latin: 'Canis lupus',
    number: 417,
    cost: 12,
    appeal: 4,
    conservation: 0,
    reputation: 0,
    enclosureSize: 4,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Predator'],
    prerequisites: [],
    continents: ['Europe'],
    ability: { Pack: null },
    soloAbility: { Pack: null },
  },
  A418_EurasianLynx: {
    type: 'animal',
    name: 'Eurasian Lynx',
    latin: 'Lynx lynx',
    number: 418,
    cost: 11,
    appeal: 2,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Predator'],
    prerequisites: { Europe: 2 },
    continents: ['Europe'],
    ability: { IconicAnimal: 'Europe' },
    soloAbility: { IconicAnimal: 'Europe' },
  },
  A419_EuropeanBadger: {
    type: 'animal',
    name: 'European Badger',
    latin: 'Meles meles',
    number: 419,
    cost: 5,
    appeal: 3,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Predator'],
    prerequisites: [],
    continents: ['Europe'],
    ability: { Boost: 'Animals' },
    soloAbility: { Boost: 'Animals' },
  },
  A420_Stoat: {
    type: 'animal',
    name: 'Stoat',
    latin: 'Mustela erminea',
    number: 420,
    cost: 4,
    appeal: 3,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Predator'],
    prerequisites: { Europe: 1 },
    continents: ['Europe'],
    ability: { Hunter: 1 },
    soloAbility: { Hunter: 1 },
  },
  A421_NewZealandFurSeal: {
    type: 'animal',
    name: 'New Zealand Fur Seal',
    latin: 'Arctocephalus forsteri',
    number: 421,
    cost: 17,
    appeal: 8,
    conservation: 0,
    reputation: 0,
    enclosureSize: 5,
    enclosureRequirements: { Water: 1, Rock: 1 },
    specialEnclosure: [],
    categories: ['Predator'],
    prerequisites: { AnimalsII: 1 },
    continents: ['Australia'],
    ability: { FullThroated: null },
    soloAbility: { FullThroated: null },
  },
  A422_AustralianSeaLion: {
    type: 'animal',
    name: 'Australian Sea Lion',
    latin: 'Neophoca cinerea - Endangered',
    number: 422,
    cost: 18,
    appeal: 7,
    conservation: 1,
    reputation: 0,
    enclosureSize: 4,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: [],
    categories: ['Predator'],
    prerequisites: { 'Partner-Zoo': 1 },
    continents: ['Australia'],
    ability: { Sunbathing: 3 },
    soloAbility: { Sunbathing: 3 },
  },
  A423_NewZealandSeaLion: {
    type: 'animal',
    name: 'New Zealand Sea Lion',
    latin: 'Phocarctos hookeri - Endangered',
    number: 423,
    cost: 17,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: [],
    categories: ['Predator'],
    prerequisites: [],
    continents: ['Australia'],
    ability: { Pack: null },
    soloAbility: { Pack: null },
  },
  A424_AustralianDingo: {
    type: 'animal',
    name: 'Australian Dingo',
    latin: 'Canis lupus dingo',
    number: 424,
    cost: 13,
    appeal: 3,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Predator'],
    prerequisites: [],
    continents: ['Australia'],
    ability: { Pack: null },
    soloAbility: { Pack: null },
  },
  A425_TasmanianDevil: {
    type: 'animal',
    name: 'Tasmanian Devil',
    latin: 'Sarcophilus harrisii - Endangered',
    number: 425,
    cost: 11,
    appeal: 4,
    conservation: 0,
    reputation: 1,
    enclosureSize: 1,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Predator'],
    prerequisites: { Science: 1 },
    continents: ['Australia'],
    ability: { Pouch: 1 },
    soloAbility: { Pouch: 1 },
  },
  A426_AfricanBushElephant: {
    type: 'animal',
    name: 'African Bush Elephant',
    latin: 'Loxodonta africana - Endangered',
    number: 426,
    cost: 36,
    appeal: 10,
    conservation: 0,
    reputation: 1,
    enclosureSize: 5,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: { AnimalsII: 1 },
    continents: ['Africa', 'Africa'],
    ability: { Resistance: null },
    soloAbility: { Resistance: null },
  },
  A427_WhiteRhinoceros: {
    type: 'animal',
    name: 'White Rhinoceros',
    latin: 'Ceratotherium simum - Near Threatened',
    number: 427,
    cost: 24,
    appeal: 9,
    conservation: 0,
    reputation: 0,
    enclosureSize: 4,
    enclosureRequirements: { Rock: 1 },
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: { Science: 1 },
    continents: ['Africa'],
    ability: { Assertion: null },
    soloAbility: { Assertion: null },
  },
  A428_NorthernGiraffe: {
    type: 'animal',
    name: 'Northern Giraffe',
    latin: 'Giraffa camelopardalis - Vulnerable',
    number: 428,
    cost: 16,
    appeal: 7,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: [],
    continents: ['Africa'],
    ability: { Boost: 'Sponsors' },
    soloAbility: { Boost: 'Sponsors' },
  },
  A429_GrevysZebra: {
    type: 'animal',
    name: "Grevy's Zebra",
    latin: 'Equus grevyi - Endangered',
    number: 429,
    cost: 12,
    appeal: 6,
    conservation: 0,
    reputation: 1,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: { Africa: 3 },
    continents: ['Africa'],
    ability: { Boost: 'Sponsors', FlockAnimal: 2 },
    soloAbility: { Boost: 'Sponsors', FlockAnimal: 2 },
  },
  A430_PygmyHippopotamus: {
    type: 'animal',
    name: 'Pygmy Hippopotamus',
    latin: 'Choeropsis liberiensis - Endangered',
    number: 430,
    cost: 15,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: { 'Partner-Zoo': 1 },
    continents: ['Africa'],
    ability: { Action: 'Sponsors' },
    soloAbility: { Action: 'Sponsors' },
  },
  A431_AsianElephant: {
    type: 'animal',
    name: 'Asian Elephant',
    latin: 'Elephas maximus - Endangered',
    number: 431,
    cost: 33,
    appeal: 8,
    conservation: 1,
    reputation: 0,
    enclosureSize: 5,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: { AnimalsII: 1 },
    continents: ['Asia', 'Asia'],
    ability: { Resistance: null },
    soloAbility: { Resistance: null },
  },
  A432_IndianRhinoceros: {
    type: 'animal',
    name: 'Indian Rhinoceros',
    latin: 'Rhinoceros unicornis - Vulnerable',
    number: 432,
    cost: 25,
    appeal: 9,
    conservation: 0,
    reputation: 0,
    enclosureSize: 4,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: { AnimalsII: 1 },
    continents: ['Asia'],
    ability: { Assertion: null },
    soloAbility: { Assertion: null },
  },
  A433_GiantPanda: {
    type: 'animal',
    name: 'Giant Panda',
    latin: 'Ailuropoda melanoleuca - Vunerable',
    number: 433,
    cost: 27,
    appeal: 10,
    conservation: 2,
    reputation: 1,
    enclosureSize: 3,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Herbivore', 'Bear'],
    prerequisites: { Herbivore: 1, Bear: 1, 'Partner-Zoo': 1 },
    continents: ['Asia'],
    ability: [],
    soloAbility: [],
  },
  A434_RedPanda: {
    type: 'animal',
    name: 'Red Panda',
    latin: 'Ailurus fulgens - Endangered',
    number: 434,
    cost: 16,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Herbivore', 'Bear'],
    prerequisites: { Science: 2 },
    continents: ['Asia'],
    ability: { Multiplier: 'Sponsors' },
    soloAbility: { Multiplier: 'Sponsors' },
  },
  A435_MalayanTapir: {
    type: 'animal',
    name: 'Malayan Tapir',
    latin: 'Tapirus indicus - Endangered',
    number: 435,
    cost: 17,
    appeal: 5,
    conservation: 0,
    reputation: 1,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: [],
    continents: ['Asia'],
    ability: { Digging: 3 },
    soloAbility: { Digging: 3 },
  },
  A436_AmericanBison: {
    type: 'animal',
    name: 'American Bison',
    latin: 'Bos bison - Near Threatened',
    number: 436,
    cost: 18,
    appeal: 4,
    conservation: 0,
    reputation: 0,
    enclosureSize: 5,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: { Americas: 3 },
    continents: ['Americas', 'Americas'],
    ability: { IconicAnimal: 'Americas' },
    soloAbility: { IconicAnimal: 'Americas' },
  },
  A437_Muskox: {
    type: 'animal',
    name: 'Muskox',
    latin: 'Ovibos moschatus',
    number: 437,
    cost: 13,
    appeal: 5,
    conservation: 0,
    reputation: 0,
    enclosureSize: 4,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: { Americas: 1 },
    continents: ['Americas'],
    ability: { SponsorMagnet: null },
    soloAbility: { SponsorMagnet: null },
  },
  A438_Reindeer: {
    type: 'animal',
    name: 'Reindeer',
    latin: 'Rangifer tarandus - Vulnerable',
    number: 438,
    cost: 12,
    appeal: 5,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: [],
    continents: ['Americas'],
    ability: { FlockAnimal: 3 },
    soloAbility: { FlockAnimal: 3 },
  },
  A439_Llama: {
    type: 'animal',
    name: 'Llama',
    latin: 'Lama glama',
    number: 439,
    cost: 10,
    appeal: 4,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: [],
    continents: ['Americas'],
    ability: { FlockAnimal: 2 },
    soloAbility: { FlockAnimal: 2 },
  },
  A440_MountainTapir: {
    type: 'animal',
    name: 'Mountain Tapir',
    latin: 'Tapirus pinchaque - Endangered',
    number: 440,
    cost: 15,
    appeal: 4,
    conservation: 1,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: { Rock: 1 },
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: [],
    continents: ['Americas'],
    ability: { Digging: 2 },
    soloAbility: { Digging: 2 },
  },
  A441_EuropeanBison: {
    type: 'animal',
    name: 'European Bison',
    latin: 'Bos bonasus - Near Threatened',
    number: 441,
    cost: 19,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 5,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: { 'Partner-Zoo': 1 },
    continents: ['Europe', 'Europe'],
    ability: { SponsorMagnet: null },
    soloAbility: { SponsorMagnet: null },
  },
  A442_Moose: {
    type: 'animal',
    name: 'Moose',
    latin: 'Alces alces',
    number: 442,
    cost: 19,
    appeal: 7,
    conservation: 0,
    reputation: 0,
    enclosureSize: 4,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: { Herbivore: 2 },
    continents: ['Europe'],
    ability: { Multiplier: 'Sponsors', FlockAnimal: 4 },
    soloAbility: { Multiplier: 'Sponsors', FlockAnimal: 4 },
  },
  A443_RedDeer: {
    type: 'animal',
    name: 'Red Deer',
    latin: 'Cervus elaphus',
    number: 443,
    cost: 12,
    appeal: 5,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: [],
    continents: ['Europe'],
    ability: { FlockAnimal: 3 },
    soloAbility: { FlockAnimal: 3 },
  },
  A444_AlpineIbex: {
    type: 'animal',
    name: 'Alpine Ibex',
    latin: 'Capra ibex',
    number: 444,
    cost: 10,
    appeal: 5,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: { Rock: 2 },
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: [],
    continents: ['Europe'],
    ability: { Jumping: 2 },
    soloAbility: { Jumping: 2 },
  },
  A445_CrestedPorcupine: {
    type: 'animal',
    name: 'Crested Porcupine',
    latin: 'Hystric cristata',
    number: 445,
    cost: 8,
    appeal: 3,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: [],
    continents: ['Europe'],
    ability: { Digging: 2 },
    soloAbility: { Digging: 2 },
  },
  A446_Dugong: {
    type: 'animal',
    name: 'Dugong',
    latin: 'Dugong dugon - Vulnerable',
    number: 446,
    cost: 25,
    appeal: 9,
    conservation: 1,
    reputation: 0,
    enclosureSize: 5,
    enclosureRequirements: { Water: 2 },
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: { AnimalsII: 1 },
    continents: ['Australia', 'Australia'],
    ability: { Digging: 4 },
    soloAbility: { Digging: 4 },
  },
  A447_RedKangaroo: {
    type: 'animal',
    name: 'Red Kangaroo',
    latin: 'Macropus rufus',
    number: 447,
    cost: 23,
    appeal: 7,
    conservation: 0,
    reputation: 0,
    enclosureSize: 4,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: [],
    continents: ['Australia'],
    ability: { Pouch: 2, FlockAnimal: 4 },
    soloAbility: { Pouch: 2, FlockAnimal: 4 },
  },
  A448_Koala: {
    type: 'animal',
    name: 'Koala',
    latin: 'Phascolarctos cinereus - Vulnerable',
    number: 448,
    cost: 21,
    appeal: 8,
    conservation: 0,
    reputation: 1,
    enclosureSize: 3,
    enclosureRequirements: { Rock: 1 },
    specialEnclosure: [],
    categories: ['Herbivore', 'Bear'],
    prerequisites: { Australia: 1 },
    continents: ['Australia'],
    ability: { Pouch: 2 },
    soloAbility: { Pouch: 2 },
  },
  A449_Platypus: {
    type: 'animal',
    name: 'Platypus',
    latin: 'Ornithorhynchus anatinus - Near Threatened',
    number: 449,
    cost: 10,
    appeal: 4,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: [],
    continents: ['Australia'],
    ability: { Venom: 1 },
    soloAbility: { Inventive: 1 },
  },
  A450_CommonWombat: {
    type: 'animal',
    name: 'Common Wombat',
    latin: 'Vombatus ursinus',
    number: 450,
    cost: 9,
    appeal: 4,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Herbivore'],
    prerequisites: [],
    continents: ['Australia'],
    ability: { Pouch: 1 },
    soloAbility: { Pouch: 1 },
  },
  A451_ProboscisMonkey: {
    type: 'animal',
    name: 'Proboscis Monkey',
    latin: 'Nasalis larvatus - Endangered',
    number: 451,
    cost: 32,
    appeal: 10,
    conservation: 2,
    reputation: 0,
    enclosureSize: 5,
    enclosureRequirements: { Rock: 1 },
    specialEnclosure: [],
    categories: ['Primate'],
    prerequisites: { Primate: 2, AnimalsII: 1 },
    continents: ['Asia'],
    ability: { Dominance: null },
    soloAbility: { Dominance: null },
  },
  A452_SenegalBushbaby: {
    type: 'animal',
    name: 'Senegal Bushbaby',
    latin: 'Galago senegalensis',
    number: 452,
    cost: 10,
    appeal: 1,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Primate'],
    prerequisites: { Africa: 2 },
    continents: ['Africa'],
    ability: { IconicAnimal: 'Africa' },
    soloAbility: { IconicAnimal: 'Africa' },
  },
  A453_CollaredMangabey: {
    type: 'animal',
    name: 'Collared Mangabey',
    latin: 'Cercocebus torquatus - Endangered',
    number: 453,
    cost: 20,
    appeal: 8,
    conservation: 0,
    reputation: 0,
    enclosureSize: 4,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Primate'],
    prerequisites: { Africa: 1 },
    continents: ['Africa'],
    ability: { Action: 'Cards' },
    soloAbility: { Action: 'Cards' },
  },
  A454_RingtailedLemur: {
    type: 'animal',
    name: 'Ring-tailed Lemur',
    latin: 'Lemur catta - Endangered',
    number: 454,
    cost: 12,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: { Rock: 1 },
    specialEnclosure: [],
    categories: ['Primate'],
    prerequisites: [],
    continents: ['Africa'],
    ability: { Sunbathing: 3 },
    soloAbility: { Sunbathing: 3 },
  },
  A455_MantledGuereza: {
    type: 'animal',
    name: 'Mantled Guereza',
    latin: 'Colobus guereza',
    number: 455,
    cost: 13,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Primate'],
    prerequisites: [],
    continents: ['Africa'],
    ability: { Clever: null },
    soloAbility: { Clever: null },
  },
  A456_BarbaryMacaque: {
    type: 'animal',
    name: 'Barbary Macaque',
    latin: 'Macaca sylvanus - Endangered',
    number: 456,
    cost: 13,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Primate'],
    prerequisites: { 'Partner-Zoo': 1 },
    continents: ['Africa'],
    ability: { Pilfering: 1 },
    soloAbility: { Sprint: 1 },
  },
  A457_Mandrill: {
    type: 'animal',
    name: 'Mandrill',
    latin: 'Mandrillus sphinx -  Vulnerable',
    number: 457,
    cost: 28,
    appeal: 9,
    conservation: 2,
    reputation: 0,
    enclosureSize: 5,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Primate', 'Primate'],
    prerequisites: { Primate: 3 },
    continents: ['Africa'],
    ability: { Multiplier: 'Cards' },
    soloAbility: { Multiplier: 'Cards' },
  },
  A458_JapaneseMacaque: {
    type: 'animal',
    name: 'Japanese Macaque',
    latin: 'Macaca fuscata',
    number: 458,
    cost: 18,
    appeal: 7,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: [],
    categories: ['Primate'],
    prerequisites: { Asia: 1 },
    continents: ['Asia'],
    ability: { Pilfering: 2 },
    soloAbility: { Sprint: 2 },
  },
  A459_RedshankedDouc: {
    type: 'animal',
    name: 'Red-shanked Douc',
    latin: 'Pygathrix nemaeus - Critically Endangered',
    number: 459,
    cost: 17,
    appeal: 7,
    conservation: 0,
    reputation: 1,
    enclosureSize: 4,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Primate'],
    prerequisites: { Science: 1 },
    continents: ['Asia'],
    ability: { Inventive: 0 },
    soloAbility: { Inventive: 0 },
  },
  A460_DuskyleafMonkey: {
    type: 'animal',
    name: 'Dusky-leaf Monkey',
    latin: 'Trachypithecus obscurus - Endangered',
    number: 460,
    cost: 12,
    appeal: 5,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Primate'],
    prerequisites: [],
    continents: ['Asia'],
    ability: { Clever: null },
    soloAbility: { Clever: null },
  },
  A461_HorsfieldsTarsier: {
    type: 'animal',
    name: "Horsfield's Tarsier",
    latin: 'Cephalopachus bancanus - Vulnerable',
    number: 461,
    cost: 14,
    appeal: 3,
    conservation: 0,
    reputation: 2,
    enclosureSize: 1,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Primate'],
    prerequisites: { 'Partner-Zoo': 1 },
    continents: ['Asia'],
    ability: { Jumping: 4 },
    soloAbility: { Jumping: 4 },
  },
  A462_NorthernPlainsGrayLangur: {
    type: 'animal',
    name: 'Northern Plains Gray Langur',
    latin: 'Semnopithecus entellus',
    number: 462,
    cost: 13,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: { Rock: 1 },
    specialEnclosure: [],
    categories: ['Primate'],
    prerequisites: [],
    continents: ['Asia'],
    ability: { Jumping: 3 },
    soloAbility: { Jumping: 3 },
  },
  A463_PanamanianWhitefacedCapuchin: {
    type: 'animal',
    name: 'Panamanian White-faced Capuchin',
    latin: 'Cebus imitator - Vulnerable',
    number: 463,
    cost: 11,
    appeal: 5,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Primate'],
    prerequisites: { 'Partner-Zoo': 1 },
    continents: ['Americas'],
    ability: { Pilfering: 1 },
    soloAbility: { Sprint: 1 },
  },
  A464_BrownSpiderMonkey: {
    type: 'animal',
    name: 'Brown Spider Monkey',
    latin: 'Ateles hybridus - Critically Endangered',
    number: 464,
    cost: 17,
    appeal: 6,
    conservation: 1,
    reputation: 0,
    enclosureSize: 4,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Primate'],
    prerequisites: { Primate: 1 },
    continents: ['Americas'],
    ability: { Inventive: 0 },
    soloAbility: { Inventive: 0 },
  },
  A465_GoldenLionTamarin: {
    type: 'animal',
    name: 'Golden Lion Tamarin',
    latin: 'Leontopithecus rosalia - Endangered',
    number: 465,
    cost: 10,
    appeal: 4,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Primate'],
    prerequisites: [],
    continents: ['Americas'],
    ability: { Clever: null },
    soloAbility: { Clever: null },
  },
  A466_BolivianRedHowler: {
    type: 'animal',
    name: 'Bolivian Red Howler',
    latin: 'Alouatta sara - Near Threatened',
    number: 466,
    cost: 12,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Primate'],
    prerequisites: [],
    continents: ['Americas'],
    ability: { Boost: 'Cards' },
    soloAbility: { Boost: 'Cards' },
  },
  A467_EcuadorianSquirellMonkey: {
    type: 'animal',
    name: 'Ecuadorian Squirell Monkey',
    latin: 'Saimiri macrodon',
    number: 467,
    cost: 12,
    appeal: 5,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Primate'],
    prerequisites: [],
    continents: ['Americas'],
    ability: { Clever: null },
    soloAbility: { Clever: null },
  },
  A468_CottontopTamarin: {
    type: 'animal',
    name: 'Cotton-top Tamarin',
    latin: 'Saguinus oedipus - Critically Endangered',
    number: 468,
    cost: 15,
    appeal: 4,
    conservation: 1,
    reputation: 1,
    enclosureSize: 1,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Primate'],
    prerequisites: { Science: 2 },
    continents: ['Americas'],
    ability: [],
    soloAbility: [],
  },
  A469_NileCrocodile: {
    type: 'animal',
    name: 'Nile Crocodile',
    latin: 'Crocodylus niloticus',
    number: 469,
    cost: 13,
    appeal: 9,
    conservation: 0,
    reputation: 0,
    enclosureSize: 5,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: { type: 'reptile-house', cubes: 3 },
    categories: ['Reptile'],
    prerequisites: { Reptile: 3 },
    continents: ['Africa'],
    ability: { Snapping: 2 },
    soloAbility: { Snapping: 2 },
  },
  A470_WesternGreenMamba: {
    type: 'animal',
    name: 'Western Green Mamba',
    latin: 'Dendroaspis viridis',
    number: 470,
    cost: 13,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: { type: 'reptile-house', cubes: 1 },
    categories: ['Reptile'],
    prerequisites: { Africa: 1, Reptile: 1 },
    continents: ['Africa'],
    ability: { Venom: 2 },
    soloAbility: { Inventive: 0 },
  },
  A471_AfricanSpurredTortoise: {
    type: 'animal',
    name: 'African Spurred Tortoise',
    latin: 'Centrochelys sulcata - Endangered',
    number: 471,
    cost: 22,
    appeal: 6,
    conservation: 1,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: [],
    specialEnclosure: { type: 'reptile-house', cubes: 2 },
    categories: ['Reptile'],
    prerequisites: [],
    continents: ['Africa'],
    ability: { Sunbathing: 3 },
    soloAbility: { Sunbathing: 3 },
  },
  A472_RockMonitor: {
    type: 'animal',
    name: 'Rock Monitor',
    latin: 'Varanus albigularis',
    number: 472,
    cost: 12,
    appeal: 5,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: { Rock: 1 },
    specialEnclosure: { type: 'reptile-house', cubes: 1 },
    categories: ['Reptile'],
    prerequisites: [],
    continents: ['Africa'],
    ability: { Sunbathing: 3 },
    soloAbility: { Sunbathing: 3 },
  },
  A473_CommonAgama: {
    type: 'animal',
    name: 'Common Agama',
    latin: 'Agama agama',
    number: 473,
    cost: 9,
    appeal: 3,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: [],
    specialEnclosure: { type: 'reptile-house', cubes: 0 },
    categories: ['Reptile'],
    prerequisites: [],
    continents: ['Africa'],
    ability: { Sunbathing: 2 },
    soloAbility: { Sunbathing: 2 },
  },
  A474_IndianRockPython: {
    type: 'animal',
    name: 'Indian Rock Python',
    latin: 'Python molurus',
    number: 474,
    cost: 14,
    appeal: 7,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: { type: 'reptile-house', cubes: 1 },
    categories: ['Reptile'],
    prerequisites: { Reptile: 2 },
    continents: ['Asia'],
    ability: { Constriction: null },
    soloAbility: { Clever: null },
  },
  A475_IndianCobra: {
    type: 'animal',
    name: 'Indian Cobra',
    latin: 'Naja naja - Vulnerable',
    number: 475,
    cost: 13,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: { type: 'reptile-house', cubes: 1 },
    categories: ['Reptile'],
    prerequisites: { Science: 2, AnimalsII: 1 },
    continents: ['Asia'],
    ability: { Hypnosis: 3 },
    soloAbility: { Determination: null },
  },
  A476_KomodoDragon: {
    type: 'animal',
    name: 'Komodo Dragon',
    latin: 'Varanus komodoensis - Vulnerable',
    number: 476,
    cost: 14,
    appeal: 2,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: [],
    specialEnclosure: { type: 'reptile-house', cubes: 2 },
    categories: ['Reptile'],
    prerequisites: { Asia: 2 },
    continents: ['Asia'],
    ability: { IconicAnimal: 'Asia' },
    soloAbility: { IconicAnimal: 'Asia' },
  },
  A477_VeiledChameleon: {
    type: 'animal',
    name: 'Veiled Chameleon',
    latin: 'Chamaeleo calyptratus',
    number: 477,
    cost: 14,
    appeal: 4,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: [],
    specialEnclosure: { type: 'reptile-house', cubes: 0 },
    categories: ['Reptile'],
    prerequisites: [],
    continents: ['Asia'],
    ability: { Snapping: 1 },
    soloAbility: { Snapping: 1 },
  },
  A478_ChineseWaterDragon: {
    type: 'animal',
    name: 'Chinese Water Dragon',
    latin: 'Physignathus cocincinus - Vulnerable',
    number: 478,
    cost: 8,
    appeal: 3,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: { type: 'reptile-house', cubes: 0 },
    categories: ['Reptile'],
    prerequisites: [],
    continents: ['Asia'],
    ability: { Sunbathing: 2 },
    soloAbility: { Sunbathing: 2 },
  },
  A479_AmericanAlligator: {
    type: 'animal',
    name: 'American Alligator',
    latin: 'Alligator mississippiensis',
    number: 479,
    cost: 18,
    appeal: 7,
    conservation: 0,
    reputation: 0,
    enclosureSize: 4,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: { type: 'reptile-house', cubes: 2 },
    categories: ['Reptile'],
    prerequisites: [],
    continents: ['Americas'],
    ability: { Snapping: 1 },
    soloAbility: { Snapping: 1 },
  },
  A480_BroadsnoutedCaiman: {
    type: 'animal',
    name: 'Broad-snouted Caiman',
    latin: 'Caiman latirostris',
    number: 480,
    cost: 16,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 4,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: { type: 'reptile-house', cubes: 2 },
    categories: ['Reptile'],
    prerequisites: [],
    continents: ['Americas'],
    ability: { Snapping: 1 },
    soloAbility: { Snapping: 1 },
  },
  A481_GalApagosGiantTortoise: {
    type: 'animal',
    name: 'Gal\u00c1pagos Giant Tortoise',
    latin: 'Chelonoidis nigra porteri - Critically Endangered',
    number: 481,
    cost: 30,
    appeal: 8,
    conservation: 2,
    reputation: 1,
    enclosureSize: 3,
    enclosureRequirements: [],
    specialEnclosure: { type: 'reptile-house', cubes: 2 },
    categories: ['Reptile'],
    prerequisites: { Americas: 2, AnimalsII: 1 },
    continents: ['Americas'],
    ability: { Sunbathing: 4 },
    soloAbility: { Sunbathing: 4 },
  },
  A482_Anaconda: {
    type: 'animal',
    name: 'Anaconda',
    latin: 'Eunectes murinus',
    number: 482,
    cost: 13,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: { type: 'reptile-house', cubes: 1 },
    categories: ['Reptile'],
    prerequisites: { 'Partner-Zoo': 1 },
    continents: ['Americas'],
    ability: { Constriction: null },
    soloAbility: { Clever: null },
  },
  A483_BoaConstrictor: {
    type: 'animal',
    name: 'Boa Constrictor',
    latin: 'Boa constrictor',
    number: 483,
    cost: 16,
    appeal: 7,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: { type: 'reptile-house', cubes: 1 },
    categories: ['Reptile'],
    prerequisites: { Science: 2 },
    continents: ['Americas'],
    ability: { Constriction: null },
    soloAbility: { Clever: null },
  },
  A484_EuropeanPondTurtle: {
    type: 'animal',
    name: 'European Pond Turtle',
    latin: 'Emys orbicularis - Near Threatened',
    number: 484,
    cost: 9,
    appeal: 4,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: { type: 'reptile-house', cubes: 1 },
    categories: ['Reptile'],
    prerequisites: [],
    continents: ['Europe'],
    ability: [],
    soloAbility: [],
  },
  A485_CommonEuropeanAdder: {
    type: 'animal',
    name: 'Common European Adder',
    latin: 'Vipera berus',
    number: 485,
    cost: 10,
    appeal: 2,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: [],
    specialEnclosure: { type: 'reptile-house', cubes: 0 },
    categories: ['Reptile'],
    prerequisites: { 'Partner-Zoo': 1 },
    continents: ['Europe'],
    ability: { Hypnosis: 3 },
    soloAbility: { Determination: null },
  },
  A486_CommonWallLizard: {
    type: 'animal',
    name: 'Common Wall Lizard',
    latin: 'Podarcis muralis',
    number: 486,
    cost: 4,
    appeal: 2,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: { Rock: 1 },
    specialEnclosure: { type: 'reptile-house', cubes: 0 },
    categories: ['Reptile'],
    prerequisites: [],
    continents: ['Europe'],
    ability: [],
    soloAbility: [],
  },
  A487_EuropeanGrassSnake: {
    type: 'animal',
    name: 'European Grass Snake',
    latin: 'Natrix natrix',
    number: 487,
    cost: 8,
    appeal: 3,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: { type: 'reptile-house', cubes: 0 },
    categories: ['Reptile'],
    prerequisites: [],
    continents: ['Europe'],
    ability: { Clever: null },
    soloAbility: { Clever: null },
  },
  A488_SlowWorm: {
    type: 'animal',
    name: 'Slow Worm',
    latin: 'Anguis fragilis - Near Threatened',
    number: 488,
    cost: 4,
    appeal: 2,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: { type: 'reptile-house', cubes: 0 },
    categories: ['Reptile'],
    prerequisites: [],
    continents: ['Europe'],
    ability: [],
    soloAbility: [],
  },
  A489_SaltwaterCrocodile: {
    type: 'animal',
    name: 'Saltwater Crocodile',
    latin: 'Crocodylus porosus',
    number: 489,
    cost: 23,
    appeal: 9,
    conservation: 0,
    reputation: 0,
    enclosureSize: 5,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: { type: 'reptile-house', cubes: 3 },
    categories: ['Reptile', 'Reptile'],
    prerequisites: { 'Partner-Zoo': 1 },
    continents: ['Australia'],
    ability: { Snapping: 2 },
    soloAbility: { Snapping: 2 },
  },
  A490_GouldsMonitor: {
    type: 'animal',
    name: "Gould's Monitor",
    latin: 'Varanus gouldii',
    number: 490,
    cost: 15,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: [],
    specialEnclosure: { type: 'reptile-house', cubes: 2 },
    categories: ['Reptile'],
    prerequisites: [],
    continents: ['Australia'],
    ability: { Scavenging: 2 },
    soloAbility: { Scavenging: 2 },
  },
  A491_FrilledLizard: {
    type: 'animal',
    name: 'Frilled Lizard',
    latin: 'Chlamydosaurus kingii',
    number: 491,
    cost: 12,
    appeal: 5,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: { Rock: 1 },
    specialEnclosure: { type: 'reptile-house', cubes: 1 },
    categories: ['Reptile'],
    prerequisites: [],
    continents: ['Australia'],
    ability: { Sprint: 1 },
    soloAbility: { Sprint: 1 },
  },
  A492_InlandTaipan: {
    type: 'animal',
    name: 'Inland Taipan',
    latin: 'Oxyuranus microlepidotus',
    number: 492,
    cost: 10,
    appeal: 5,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: { Rock: 1 },
    specialEnclosure: { type: 'reptile-house', cubes: 1 },
    categories: ['Reptile'],
    prerequisites: { Australia: 1, Science: 1 },
    continents: ['Australia'],
    ability: { Venom: 2 },
    soloAbility: { Inventive: 0 },
  },
  A493_ThornyDevil: {
    type: 'animal',
    name: 'Thorny Devil',
    latin: 'Moloch horridus',
    number: 493,
    cost: 6,
    appeal: 3,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: { Rock: 1 },
    specialEnclosure: { type: 'reptile-house', cubes: 0 },
    categories: ['Reptile'],
    prerequisites: [],
    continents: ['Australia'],
    ability: [],
    soloAbility: [],
  },
  A494_AfricanOstrich: {
    type: 'animal',
    name: 'African Ostrich',
    latin: 'Struthio camelus',
    number: 494,
    cost: 20,
    appeal: 8,
    conservation: 0,
    reputation: 0,
    enclosureSize: 5,
    enclosureRequirements: [],
    specialEnclosure: { type: 'large-bird-aviary', cubes: 4 },
    categories: ['Bird'],
    prerequisites: [],
    continents: ['Africa'],
    ability: { Sprint: 2 },
    soloAbility: { Sprint: 2 },
  },
  A495_SecretaryBird: {
    type: 'animal',
    name: 'Secretary Bird',
    latin: 'Sagittarius serpentarius - Endangered',
    number: 495,
    cost: 14,
    appeal: 4,
    conservation: 1,
    reputation: 0,
    enclosureSize: 4,
    enclosureRequirements: [],
    specialEnclosure: { type: 'large-bird-aviary', cubes: 1 },
    categories: ['Bird'],
    prerequisites: [],
    continents: ['Africa'],
    ability: [],
    soloAbility: [],
  },
  A496_Marabou: {
    type: 'animal',
    name: 'Marabou',
    latin: 'Leptoptilos crumeniferus',
    number: 496,
    cost: 10,
    appeal: 4,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: [],
    specialEnclosure: { type: 'large-bird-aviary', cubes: 1 },
    categories: ['Bird'],
    prerequisites: [],
    continents: ['Africa'],
    ability: { Scavenging: 2 },
    soloAbility: { Scavenging: 2 },
  },
  A497_LesserFlamingo: {
    type: 'animal',
    name: 'Lesser Flamingo',
    latin: 'Phoeniconaias minor - Near Threatened',
    number: 497,
    cost: 15,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: [],
    categories: ['Bird'],
    prerequisites: [],
    continents: ['Africa'],
    ability: { Posturing: 1 },
    soloAbility: { Posturing: 1 },
  },
  A498_Shoebill: {
    type: 'animal',
    name: 'Shoebill',
    latin: 'Balaeniceps rex - Vulnerable',
    number: 498,
    cost: 9,
    appeal: 3,
    conservation: 1,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: [],
    specialEnclosure: { type: 'large-bird-aviary', cubes: 1 },
    categories: ['Bird'],
    prerequisites: { Science: 2 },
    continents: ['Africa'],
    ability: [],
    soloAbility: [],
  },
  A499_CinereousVulture: {
    type: 'animal',
    name: 'Cinereous Vulture',
    latin: 'Aegypius monachus - Near Threatened',
    number: 499,
    cost: 16,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 5,
    enclosureRequirements: [],
    specialEnclosure: { type: 'large-bird-aviary', cubes: 1 },
    categories: ['Bird'],
    prerequisites: [],
    continents: ['Asia'],
    ability: { Scavenging: 3 },
    soloAbility: { Scavenging: 3 },
  },
  A500_LongbilledVulture: {
    type: 'animal',
    name: 'Long-billed Vulture',
    latin: 'Gyps indicus - Critically Endangered',
    number: 500,
    cost: 20,
    appeal: 5,
    conservation: 1,
    reputation: 1,
    enclosureSize: 4,
    enclosureRequirements: { Rock: 1 },
    specialEnclosure: { type: 'large-bird-aviary', cubes: 1 },
    categories: ['Bird'],
    prerequisites: { Science: 1 },
    continents: ['Asia'],
    ability: { Scavenging: 3 },
    soloAbility: { Scavenging: 3 },
  },
  A501_IndianPeafowl: {
    type: 'animal',
    name: 'Indian Peafowl',
    latin: 'Pavo cristatus',
    number: 501,
    cost: 18,
    appeal: 7,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Bird'],
    prerequisites: { Asia: 1 },
    continents: ['Asia'],
    ability: { Posturing: 2 },
    soloAbility: { Posturing: 2 },
  },
  A502_GreatHornbill: {
    type: 'animal',
    name: 'Great Hornbill',
    latin: 'Buceros bicornis - Vulnerable',
    number: 502,
    cost: 13,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Bird'],
    prerequisites: [],
    continents: ['Asia'],
    ability: { Boost: 'Build' },
    soloAbility: { Boost: 'Build' },
  },
  A503_SnowyOwl: {
    type: 'animal',
    name: 'Snowy Owl',
    latin: 'Bubo scandiacus - Vulnerable',
    number: 503,
    cost: 11,
    appeal: 4,
    conservation: 0,
    reputation: 1,
    enclosureSize: 1,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Bird'],
    prerequisites: { Bird: 2 },
    continents: ['Asia'],
    ability: { Perception: 4 },
    soloAbility: { Perception: 4 },
  },
  A504_AndeanCondor: {
    type: 'animal',
    name: 'Andean Condor',
    latin: 'Vultur gryphus - Vulnerable',
    number: 504,
    cost: 17,
    appeal: 7,
    conservation: 0,
    reputation: 1,
    enclosureSize: 5,
    enclosureRequirements: { Rock: 1 },
    specialEnclosure: { type: 'large-bird-aviary', cubes: 1 },
    categories: ['Bird'],
    prerequisites: { Bird: 1 },
    continents: ['Americas'],
    ability: { Scavenging: 4 },
    soloAbility: { Scavenging: 4 },
  },
  A505_BaldEagle: {
    type: 'animal',
    name: 'Bald Eagle',
    latin: 'Haliaeetus leucocephalus',
    number: 505,
    cost: 23,
    appeal: 8,
    conservation: 0,
    reputation: 0,
    enclosureSize: 4,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: { type: 'large-bird-aviary', cubes: 1 },
    categories: ['Bird'],
    prerequisites: { AnimalsII: 1 },
    continents: ['Americas'],
    ability: { Determination: null },
    soloAbility: { Determination: null },
  },
  A506_KingVulture: {
    type: 'animal',
    name: 'King Vulture',
    latin: 'Sarcoramphus papa',
    number: 506,
    cost: 12,
    appeal: 9,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: [],
    specialEnclosure: { type: 'large-bird-aviary', cubes: 1 },
    categories: ['Bird'],
    prerequisites: { Bird: 3 },
    continents: ['Americas'],
    ability: { Scavenging: 5 },
    soloAbility: { Scavenging: 5 },
  },
  A507_GreaterRhea: {
    type: 'animal',
    name: 'Greater Rhea',
    latin: 'Rhea americana - Near Threatened',
    number: 507,
    cost: 12,
    appeal: 5,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Bird'],
    prerequisites: [],
    continents: ['Americas'],
    ability: { Sprint: 1 },
    soloAbility: { Sprint: 1 },
  },
  A508_ScarletMacaw: {
    type: 'animal',
    name: 'Scarlet Macaw',
    latin: 'Ara macao',
    number: 508,
    cost: 16,
    appeal: 4,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Bird'],
    prerequisites: { 'Partner-Zoo': 1 },
    continents: ['Americas'],
    ability: { Posturing: 3 },
    soloAbility: { Posturing: 3 },
  },
  A509_GoldenEagle: {
    type: 'animal',
    name: 'Golden Eagle',
    latin: 'Aquila chrysaetos',
    number: 509,
    cost: 20,
    appeal: 7,
    conservation: 0,
    reputation: 0,
    enclosureSize: 5,
    enclosureRequirements: { Rock: 1 },
    specialEnclosure: { type: 'large-bird-aviary', cubes: 1 },
    categories: ['Bird'],
    prerequisites: { AnimalsII: 1 },
    continents: ['Europe'],
    ability: { Determination: null },
    soloAbility: { Determination: null },
  },
  A510_WhiteStork: {
    type: 'animal',
    name: 'White Stork',
    latin: 'Ciconia ciconia',
    number: 510,
    cost: 9,
    appeal: 4,
    conservation: 0,
    reputation: 0,
    enclosureSize: 4,
    enclosureRequirements: [],
    specialEnclosure: { type: 'large-bird-aviary', cubes: 1 },
    categories: ['Bird'],
    prerequisites: { Europe: 1 },
    continents: ['Europe'],
    ability: { Multiplier: 'Build' },
    soloAbility: { Multiplier: 'Build' },
  },
  A511_GreaterFlamingo: {
    type: 'animal',
    name: 'Greater Flamingo',
    latin: 'Phoenicopterus roseus',
    number: 511,
    cost: 16,
    appeal: 7,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: { Water: 1 },
    specialEnclosure: [],
    categories: ['Bird'],
    prerequisites: [],
    continents: ['Europe'],
    ability: { Posturing: 1 },
    soloAbility: { Posturing: 1 },
  },
  A512_EurasianEagleowl: {
    type: 'animal',
    name: 'Eurasian Eagle-owl',
    latin: 'Bubo bubo',
    number: 512,
    cost: 10,
    appeal: 4,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Bird'],
    prerequisites: { 'Partner-Zoo': 1 },
    continents: ['Europe'],
    ability: { Perception: 4 },
    soloAbility: { Perception: 4 },
  },
  A513_BarnOwl: {
    type: 'animal',
    name: 'Barn Owl',
    latin: 'Tyto alba',
    number: 513,
    cost: 12,
    appeal: 3,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Bird'],
    prerequisites: [],
    continents: ['Europe'],
    ability: { Perception: 4 },
    soloAbility: { Perception: 4 },
  },
  A514_Emu: {
    type: 'animal',
    name: 'Emu',
    latin: 'Dromaius novaehollandiae',
    number: 514,
    cost: 22,
    appeal: 7,
    conservation: 0,
    reputation: 0,
    enclosureSize: 5,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Bird'],
    prerequisites: { Australia: 2 },
    continents: ['Australia'],
    ability: { Peacocking: null },
    soloAbility: { Peacocking: null },
  },
  A515_AustralianPelican: {
    type: 'animal',
    name: 'Australian Pelican',
    latin: 'Pelecanus conspicillatus',
    number: 515,
    cost: 13,
    appeal: 5,
    conservation: 0,
    reputation: 0,
    enclosureSize: 4,
    enclosureRequirements: { Water: 2 },
    specialEnclosure: [],
    categories: ['Bird'],
    prerequisites: [],
    continents: ['Australia'],
    ability: { Action: 'Build' },
    soloAbility: { Action: 'Build' },
  },
  A516_NorhternCassowary: {
    type: 'animal',
    name: 'Norhtern Cassowary',
    latin: 'Casuarius unappendiculatus',
    number: 516,
    cost: 12,
    appeal: 6,
    conservation: 0,
    reputation: 0,
    enclosureSize: 3,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Bird'],
    prerequisites: { 'Partner-Zoo': 1 },
    continents: ['Australia'],
    ability: { Multiplier: 'Build' },
    soloAbility: { Multiplier: 'Build' },
  },
  A517_LaughingKookaburra: {
    type: 'animal',
    name: 'Laughing Kookaburra',
    latin: 'Dacelo novaeguineae',
    number: 517,
    cost: 9,
    appeal: 0,
    conservation: 0,
    reputation: 0,
    enclosureSize: 2,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Bird'],
    prerequisites: { Australia: 1 },
    continents: ['Australia'],
    ability: { IconicAnimal: 'Australia' },
    soloAbility: { IconicAnimal: 'Australia' },
  },
  A518_LesserBirdofparadise: {
    type: 'animal',
    name: 'Lesser Bird-of-paradise',
    latin: 'Paradisaea minor',
    number: 518,
    cost: 15,
    appeal: 5,
    conservation: 0,
    reputation: 0,
    enclosureSize: 1,
    enclosureRequirements: [],
    specialEnclosure: [],
    categories: ['Bird'],
    prerequisites: [],
    continents: ['Australia'],
    ability: { Posturing: 1 },
    soloAbility: { Posturing: 1 },
  },
  A519_domesticGoat: {
    type: 'animal',
    name: '(domestic) Goat',
    latin: 'Capra aegagrus hircus',
    number: 519,
    cost: 7,
    appeal: 0,
    conservation: 0,
    reputation: 0,
    enclosureSize: 0,
    enclosureRequirements: [],
    specialEnclosure: { type: 'petting-zoo', cubes: 1 },
    categories: ['Pet'],
    prerequisites: [],
    continents: [],
    ability: { PettingZooAnimal: null },
    soloAbility: { PettingZooAnimal: null },
  },
  A520_Sheep: {
    type: 'animal',
    name: 'Sheep',
    latin: 'Ovis gmelini aries',
    number: 520,
    cost: 7,
    appeal: 0,
    conservation: 0,
    reputation: 0,
    enclosureSize: 0,
    enclosureRequirements: [],
    specialEnclosure: { type: 'petting-zoo', cubes: 1 },
    categories: ['Pet'],
    prerequisites: [],
    continents: [],
    ability: { PettingZooAnimal: null },
    soloAbility: { PettingZooAnimal: null },
  },
  A521_Horse: {
    type: 'animal',
    name: 'Horse',
    latin: 'Equus caballus',
    number: 521,
    cost: 7,
    appeal: 0,
    conservation: 0,
    reputation: 1,
    enclosureSize: 0,
    enclosureRequirements: [],
    specialEnclosure: { type: 'petting-zoo', cubes: 1 },
    categories: ['Pet'],
    prerequisites: [],
    continents: [],
    ability: { PettingZooAnimal: null },
    soloAbility: { PettingZooAnimal: null },
  },
  A522_Donkey: {
    type: 'animal',
    name: 'Donkey',
    latin: 'Equus asinus asinus',
    number: 522,
    cost: 7,
    appeal: 0,
    conservation: 0,
    reputation: 0,
    enclosureSize: 0,
    enclosureRequirements: [],
    specialEnclosure: { type: 'petting-zoo', cubes: 1 },
    categories: ['Pet'],
    prerequisites: [],
    continents: [],
    ability: { PettingZooAnimal: null, Inventive: 0 },
    soloAbility: { PettingZooAnimal: null, Inventive: 0 },
  },
  A523_DomesticRabbit: {
    type: 'animal',
    name: 'Domestic Rabbit',
    latin: 'Oryctolagus cuniculus d. dom.',
    number: 523,
    cost: 7,
    appeal: 0,
    conservation: 0,
    reputation: 0,
    enclosureSize: 0,
    enclosureRequirements: [],
    specialEnclosure: { type: 'petting-zoo', cubes: 1 },
    categories: ['Pet'],
    prerequisites: [],
    continents: [],
    ability: { PettingZooAnimal: null },
    soloAbility: { PettingZooAnimal: null },
  },
  A524_Mangalica: {
    type: 'animal',
    name: 'Mangalica',
    latin: 'Sus scrofa form. domestica',
    number: 524,
    cost: 7,
    appeal: 0,
    conservation: 0,
    reputation: 0,
    enclosureSize: 0,
    enclosureRequirements: [],
    specialEnclosure: { type: 'petting-zoo', cubes: 1 },
    categories: ['Pet'],
    prerequisites: [],
    continents: [],
    ability: { PettingZooAnimal: null },
    soloAbility: { PettingZooAnimal: null },
  },
  A525_GuineaPig: {
    type: 'animal',
    name: 'Guinea Pig',
    latin: 'Cavia porcellus form. domestica',
    number: 525,
    cost: 7,
    appeal: 0,
    conservation: 0,
    reputation: 0,
    enclosureSize: 0,
    enclosureRequirements: [],
    specialEnclosure: { type: 'petting-zoo', cubes: 1 },
    categories: ['Pet'],
    prerequisites: [],
    continents: [],
    ability: { PettingZooAnimal: null, Digging: 1 },
    soloAbility: { PettingZooAnimal: null, Digging: 1 },
  },
  A526_Alpaca: {
    type: 'animal',
    name: 'Alpaca',
    latin: 'Vicugna pacos',
    number: 526,
    cost: 7,
    appeal: 0,
    conservation: 0,
    reputation: 0,
    enclosureSize: 0,
    enclosureRequirements: [],
    specialEnclosure: { type: 'petting-zoo', cubes: 1 },
    categories: ['Pet'],
    prerequisites: [],
    continents: [],
    ability: { PettingZooAnimal: null },
    soloAbility: { PettingZooAnimal: null },
  },
  A527_CoconutLorikeet: {
    type: 'animal',
    name: 'Coconut Lorikeet',
    latin: 'Trichoglossus haematodus',
    number: 527,
    cost: 7,
    appeal: 0,
    conservation: 0,
    reputation: 0,
    enclosureSize: 0,
    enclosureRequirements: [],
    specialEnclosure: { type: 'petting-zoo', cubes: 1 },
    categories: ['Pet'],
    prerequisites: [],
    continents: [],
    ability: { PettingZooAnimal: null },
    soloAbility: { PettingZooAnimal: null },
  },
  A528_BennettsWallaby: {
    type: 'animal',
    name: "Bennett's Wallaby",
    latin: 'Macropus rufogriseus',
    number: 528,
    cost: 7,
    appeal: 0,
    conservation: 0,
    reputation: 0,
    enclosureSize: 0,
    enclosureRequirements: [],
    specialEnclosure: { type: 'petting-zoo', cubes: 1 },
    categories: ['Pet'],
    prerequisites: [],
    continents: [],
    ability: { PettingZooAnimal: null, Pouch: 1 },
    soloAbility: { PettingZooAnimal: null, Pouch: 1 },
  },
  P101_SpeciesDiversity: {
    type: 'baseProject',
    name: 'Species Diversity',
    number: 101,
    desc: 'Requires different **animal category** icons in your zoo.',
    icon: 'all-animals',
    category: '',
    slots: [
      { condition: 5, gain: { conservation: 5 } },
      { condition: 4, gain: { conservation: 3 } },
      { condition: 3, gain: { conservation: 2 } },
    ],
  },
  P102_HabitatDiversity: {
    type: 'baseProject',
    name: 'Habitat Diversity',
    number: 102,
    desc: 'Requires different **continent** icons in your zoo.',
    icon: 'all-continents',
    category: '',
    slots: [
      { condition: 5, gain: { conservation: 5 } },
      { condition: 4, gain: { conservation: 3 } },
      { condition: 3, gain: { conservation: 2 } },
    ],
  },
  P103_Africa: {
    type: 'baseProject',
    name: 'Africa',
    number: 103,
    desc: 'Requires **Africa** icons in your zoo.',
    icon: 'Africa',
    category: 'icons',
    slots: [
      { condition: 5, gain: { conservation: 5 } },
      { condition: 4, gain: { conservation: 3 } },
      { condition: 2, gain: { conservation: 2 } },
    ],
  },
  P104_Americas: {
    type: 'baseProject',
    name: 'Americas',
    number: 104,
    desc: 'Requires **Americas** icons in your zoo.',
    icon: 'Americas',
    category: 'icons',
    slots: [
      { condition: 5, gain: { conservation: 5 } },
      { condition: 4, gain: { conservation: 3 } },
      { condition: 2, gain: { conservation: 2 } },
    ],
  },
  P105_Australia: {
    type: 'baseProject',
    name: 'Australia',
    number: 105,
    desc: 'Requires **Australia** icons in your zoo.',
    icon: 'Australia',
    category: 'icons',
    slots: [
      { condition: 5, gain: { conservation: 5 } },
      { condition: 4, gain: { conservation: 4 } },
      { condition: 2, gain: { conservation: 2 } },
    ],
  },
  P106_Asia: {
    type: 'baseProject',
    name: 'Asia',
    number: 106,
    desc: 'Requires **Asia** icons in your zoo.',
    icon: 'Asia',
    category: 'icons',
    slots: [
      { condition: 5, gain: { conservation: 5 } },
      { condition: 4, gain: { conservation: 3 } },
      { condition: 2, gain: { conservation: 2 } },
    ],
  },
  P107_Europe: {
    type: 'baseProject',
    name: 'Europe',
    number: 107,
    desc: 'Requires **Europe** icons in your zoo.',
    icon: 'Europe',
    category: 'icons',
    slots: [
      { condition: 5, gain: { conservation: 5 } },
      { condition: 4, gain: { conservation: 4 } },
      { condition: 2, gain: { conservation: 2 } },
    ],
  },
  P108_Primates: {
    type: 'baseProject',
    name: 'Primates',
    number: 108,
    desc: 'Requires **primate** icons in your zoo.',
    icon: 'Primate',
    category: 'icons',
    slots: [
      { condition: 5, gain: { conservation: 5 } },
      { condition: 4, gain: { conservation: 4 } },
      { condition: 2, gain: { conservation: 2 } },
    ],
  },
  P109_Reptiles: {
    type: 'baseProject',
    name: 'Reptiles',
    number: 109,
    desc: 'Requires **reptile** icons in your zoo.',
    icon: 'Reptile',
    category: 'icons',
    slots: [
      { condition: 5, gain: { conservation: 5 } },
      { condition: 4, gain: { conservation: 4 } },
      { condition: 2, gain: { conservation: 2 } },
    ],
  },
  P110_Predators: {
    type: 'baseProject',
    name: 'Predators',
    number: 110,
    desc: 'Requires **predator** icons in your zoo.',
    icon: 'Predator',
    category: 'icons',
    slots: [
      { condition: 5, gain: { conservation: 5 } },
      { condition: 4, gain: { conservation: 4 } },
      { condition: 2, gain: { conservation: 2 } },
    ],
  },
  P111_Herbivores: {
    type: 'baseProject',
    name: 'Herbivores',
    number: 111,
    desc: 'Requires **hebivore** icons in your zoo.',
    icon: 'Herbivore',
    category: 'icons',
    slots: [
      { condition: 5, gain: { conservation: 5 } },
      { condition: 4, gain: { conservation: 4 } },
      { condition: 2, gain: { conservation: 2 } },
    ],
  },
  P112_Birds: {
    type: 'baseProject',
    name: 'Birds',
    number: 112,
    desc: 'Requires **bird** icons in your zoo.',
    icon: 'Bird',
    category: 'icons',
    slots: [
      { condition: 5, gain: { conservation: 5 } },
      { condition: 4, gain: { conservation: 4 } },
      { condition: 2, gain: { conservation: 2 } },
    ],
  },
  P113_ReleaseBavarian: {
    type: 'project',
    name: 'Bavarian Forest national park',
    number: 113,
    desc: '**Release** 1 animal with a **Europe** icon into the wild.',
    icon: 'Europe',
    category: 'release',
    slots: [
      { condition: { size: 4 }, gain: { conservation: 5, reputation: 1 } },
      { condition: { size: 3 }, gain: { conservation: 4, reputation: 1 } },
      { condition: { size: 2 }, gain: { conservation: 3, reputation: 1 } },
    ],
  },
  P114_ReleaseYosemite: {
    type: 'project',
    name: 'Yosemite national park',
    number: 114,
    desc: '**Release** 1 animal with an **Americas** icon into the wild.',
    icon: 'Americas',
    category: 'release',
    slots: [
      { condition: { size: 4 }, gain: { conservation: 5, reputation: 1 } },
      { condition: { size: 3 }, gain: { conservation: 4, reputation: 1 } },
      { condition: { size: 2 }, gain: { conservation: 3, reputation: 1 } },
    ],
  },
  P115_ReleaseAngthong: {
    type: 'project',
    name: 'Angthong national park',
    number: 115,
    desc: '**Release** 1 animal with an **Asia** icon into the wild.',
    icon: 'Asia',
    category: 'release',
    slots: [
      { condition: { size: 4 }, gain: { conservation: 5, reputation: 1 } },
      { condition: { size: 3 }, gain: { conservation: 4, reputation: 1 } },
      { condition: { size: 2 }, gain: { conservation: 3, reputation: 1 } },
    ],
  },
  P116_ReleaseSerengeti: {
    type: 'project',
    name: 'Serengeti national park',
    number: 116,
    desc: '**Release** 1 animal with an **Africa** icon into the wild.',
    icon: 'Africa',
    category: 'release',
    slots: [
      { condition: { size: 4 }, gain: { conservation: 5, reputation: 1 } },
      { condition: { size: 3 }, gain: { conservation: 4, reputation: 1 } },
      { condition: { size: 2 }, gain: { conservation: 3, reputation: 1 } },
    ],
  },
  P117_ReleaseBlueMountain: {
    type: 'project',
    name: 'Blue mountains national park',
    number: 117,
    desc: '**Release** 1 animal with an **Australia** icon into the wild.',
    icon: 'Australia',
    category: 'release',
    slots: [
      { condition: { size: 4 }, gain: { conservation: 5, reputation: 1 } },
      { condition: { size: 3 }, gain: { conservation: 4, reputation: 1 } },
      { condition: { size: 2 }, gain: { conservation: 3, reputation: 1 } },
    ],
  },
  P118_ReleaseSavanna: {
    type: 'project',
    name: 'Savanna',
    number: 118,
    desc: '**Release 1 predator** into the wild.',
    icon: 'Predator',
    category: 'release',
    slots: [
      { condition: { size: 4 }, gain: { conservation: 5, reputation: 1 } },
      { condition: { size: 3 }, gain: { conservation: 4, reputation: 1 } },
      { condition: { size: 2 }, gain: { conservation: 3, reputation: 1 } },
    ],
  },
  P123_BirdBreeding: {
    type: 'project',
    name: 'Bird breeding program',
    number: 123,
    desc: 'Requires 1 **bird** and a **partner zoo** of the same continent.',
    icon: 'Bird',
    category: 'breed',
    slots: [
      { gain: { conservation: 2, reputation: 2 } },
      { gain: { conservation: 1, reputation: 2 } },
      { gain: { conservation: 2 } },
    ],
  },
  P124_PredatorBreeding: {
    type: 'project',
    name: 'Predator breeding program',
    number: 124,
    desc: 'Requires 1 **predator** and a **partner zoo** of the same continent.',
    icon: 'Predator',
    category: 'breed',
    slots: [
      { gain: { conservation: 2, reputation: 2 } },
      { gain: { conservation: 1, reputation: 2 } },
      { gain: { conservation: 2 } },
    ],
  },
  P125_ReptileBreeding: {
    type: 'project',
    name: 'Reptile breeding program',
    number: 125,
    desc: 'Requires 1 **reptile** and a **partner zoo** of the same continent.',
    icon: 'Reptile',
    category: 'breed',
    slots: [
      { gain: { conservation: 2, reputation: 2 } },
      { gain: { conservation: 1, reputation: 2 } },
      { gain: { conservation: 2 } },
    ],
  },
  P126_HerbivoreBreeding: {
    type: 'project',
    name: 'Herbivore breeding program',
    number: 126,
    desc: 'Requires 1 **herbivore** and a **partner zoo** of the same continent.',
    icon: 'Herbivore',
    category: 'breed',
    slots: [
      { gain: { conservation: 2, reputation: 2 } },
      { gain: { conservation: 1, reputation: 2 } },
      { gain: { conservation: 2 } },
    ],
  },
  P127_PrimateBreeding: {
    type: 'project',
    name: 'Primate breeding program',
    number: 127,
    desc: 'Requires 1 **primate** and a **partner zoo** of the same continent.',
    icon: 'Primate',
    category: 'breed',
    slots: [
      { gain: { conservation: 2, reputation: 2 } },
      { gain: { conservation: 1, reputation: 2 } },
      { gain: { conservation: 2 } },
    ],
  },
  P128_Aquatic: {
    type: 'project',
    name: 'Aquatic',
    number: 128,
    desc: 'Requires **water** icons in your zoo.',
    icon: 'Water',
    category: 'icons',
    slots: [
      { condition: 5, gain: { conservation: 4 } },
      { condition: 4, gain: { conservation: 3 } },
      { condition: 2, gain: { conservation: 2 } },
    ],
  },
  P129_Geological: {
    type: 'project',
    name: 'Geological',
    number: 129,
    desc: 'Requires **rock** icons in your zoo.',
    icon: 'Rock',
    category: 'icons',
    slots: [
      { condition: 5, gain: { conservation: 4 } },
      { condition: 4, gain: { conservation: 3 } },
      { condition: 2, gain: { conservation: 2 } },
    ],
  },
  P130_SmallAnimals: {
    type: 'project',
    name: 'Small Animals',
    number: 130,
    desc: 'Requires **small animals** in your zoo.',
    icon: 'ANIMAL-SIZE-2',
    category: '',
    slots: [
      { condition: 8, gain: { conservation: 4 } },
      { condition: 5, gain: { conservation: 3 } },
      { condition: 2, gain: { conservation: 2 } },
    ],
  },
  P131_LargeAnimals: {
    type: 'project',
    name: 'Large Animals',
    number: 131,
    desc: 'Requires **large animals** in your zoo.',
    icon: 'ANIMAL-SIZE-4',
    category: '',
    slots: [
      { condition: 4, gain: { conservation: 4 } },
      { condition: 3, gain: { conservation: 3 } },
      { condition: 2, gain: { conservation: 2 } },
    ],
  },
  P132_Research: {
    type: 'project',
    name: 'Research',
    number: 132,
    desc: 'Requires **research** icons in your zoo.',
    icon: 'Science',
    category: 'icons',
    slots: [
      { condition: 5, gain: { conservation: 4 } },
      { condition: 4, gain: { conservation: 3 } },
      { condition: 2, gain: { conservation: 2 } },
    ],
  },
  F001_LargeAnimalZoo: {
    type: 'scoring',
    name: 'Large Animal Zoo',
    number: 1,
    desc: 'Gain <CONSERVATION> for **large animals** in your zoo',
    icon: 'ANIMAL-SIZE-4',
    scoreMap: { 1: 1, 2: 2, 4: 3, 5: 4 },
  },
  F002_SmallAnimalZoo: {
    type: 'scoring',
    name: 'Small Animal Zoo',
    number: 2,
    desc: 'Gain <CONSERVATION> for **small animals** in your zoo',
    icon: 'ANIMAL-SIZE-2',
    scoreMap: { 3: 1, 6: 2, 8: 3, 10: 4 },
  },
  F003_ResearchZoo: {
    type: 'scoring',
    name: 'Research Zoo',
    number: 3,
    desc: 'Gain <CONSERVATION> for **research icons** in your zoo',
    icon: 'Science',
    scoreMap: { 3: 1, 4: 2, 5: 3, 6: 4 },
  },
  F004_ArchitecturalZoo: {
    type: 'scoring',
    name: 'Architectural Zoo',
    number: 4,
    desc: 'Gain <CONSERVATION> for **building** of your zoo.',
    icon: 'ENCLOSURE-REGULAR',
    scoreMap: [],
  },
  F005_ConservationZoo: {
    type: 'scoring',
    name: 'Conservation Zoo',
    number: 5,
    desc: 'Gain <CONSERVATION> for **supporting conservation icons** in your zoo',
    icon: 'PLACE-CUBE',
    scoreMap: { 3: 1, 4: 2, 5: 3, 6: 4 },
  },
  F006_NaturalistsZoo: {
    type: 'scoring',
    name: "Naturalists' Zoo",
    number: 6,
    desc: 'Gain <CONSERVATION> for **empty building spaces** in your zoo',
    icon: 'ENCLOSURE-EMPTY',
    scoreMap: { 6: 1, 12: 2, 18: 3, 24: 4 },
  },
  F007_FavoriteZoo: {
    type: 'scoring',
    name: 'Favorite Zoo',
    number: 7,
    desc: 'Gain <CONSERVATION> for **reputation** in your zoo',
    icon: 'reputation',
    scoreMap: { 6: 1, 9: 2, 12: 3, 15: 4 },
  },
  F008_SponsoredZoo: {
    type: 'scoring',
    name: 'Sponsored Zoo',
    number: 8,
    desc: 'Gain <CONSERVATION> for **sponsor cards** in your zoo',
    icon: 'SPONSOR-CARD',
    scoreMap: { 3: 1, 6: 2, 8: 3, 10: 4 },
  },
  F009_DiverseSpeciesZoo: {
    type: 'scoring',
    name: 'Diverse species Zoo',
    number: 9,
    desc: 'TODO',
    icon: 'ALL-ANIMALS',
    scoreMap: [],
  },
  F010_ClimbingPark: {
    type: 'scoring',
    name: 'Climbing Park',
    number: 10,
    desc: 'Gain <CONSERVATION> for **rock icons** in your zoo',
    icon: 'ROCK',
    scoreMap: { 1: 1, 3: 2, 5: 3, 7: 4 },
  },
  F011_AquaticPark: {
    type: 'scoring',
    name: 'Aquatic Park',
    number: 11,
    desc: 'Gain <CONSERVATION> for **water icons** in your zoo',
    icon: 'WATER',
    scoreMap: { 2: 1, 4: 2, 6: 3, 8: 4 },
  },
};
const MAPS_DATA = {
  A: {
    id: 'A',
    name: '',
    terrains: {
      Water: ['2_1', '2_11', '3_12', '4_1', '5_8', '6_7', '7_0', '8_1', '8_3'],
      Rock: ['1_0', '1_2', '1_12', '2_3', '3_0', '5_4', '6_9'],
    },
    upgradeNeeded: ['7_12', '8_11'],
    bonuses: {
      '0_1': { reputation: 2 },
      '0_3': { xtoken: 1 },
      '2_5': { 'take-in-range': 1 },
      '2_9': { money: 5 },
      '3_2': { money: 5 },
      '4_7': { xtoken: 1 },
      '5_0': { xtoken: 1 },
      '5_6': { 'take-in-range': 1 },
      '5_10': { 'take-in-range': 1 },
      '7_2': { 'add-worker': 1 },
      '7_10': { reputation: 2 },
      '8_5': { money: 10 },
    },
    bonusSpaces: [
      { type: 'income', bonus: { Snapping: 1 } },
      { type: 'income', bonus: { 'enclosure-size-2': 1 } },
      { type: 'income', bonus: { money: 5 } },
      { type: 'income', bonus: { reputation: 1 } },
      { type: 'bonus', bonus: { 'add-worker': 1 } },
      { type: 'bonus', bonus: { money: 12 } },
      { type: 'bonus', bonus: { xtoken: 3 } },
    ],
    lastWorkerBonus: { conservation: 2 },
    partnerZooBonuses: { 2: { 'upgrade-card': 1 }, 3: { 'add-worker': 1 }, 4: { conservation: 2 } },
    facBonuses: { 2: { 'upgrade-card': 1 }, 3: { conservation: 2 } },
  },
  0: {
    id: '0',
    name: '',
    terrains: {
      Water: ['0_1', '0_3', '1_0', '1_10', '2_7', '3_0', '5_4', '7_12', '8_9', '8_11'],
      Rock: ['0_11', '1_12', '2_1', '3_2', '5_8', '5_12', '6_3', '6_9', '6_11'],
    },
    upgradeNeeded: ['6_5', '7_4'],
    bonuses: {
      '0_9': { reputation: 2 },
      '1_2': { 'take-in-range': 1 },
      '2_5': { 'take-in-range': 1 },
      '3_8': { xtoken: 1 },
      '3_12': { 'take-in-range': 1 },
      '4_1': { xtoken: 1 },
      '4_5': { money: 10 },
      '5_6': { Clever: 1 },
      '5_10': { xtoken: 1 },
      '7_2': { money: 5 },
      '7_10': { reputation: 2 },
      '8_7': { money: 5 },
    },
    bonusSpaces: [
      { type: 'income', bonus: { Snapping: 1 } },
      { type: 'income', bonus: { 'enclosure-size-2': 1 } },
      { type: 'income', bonus: { money: 5 } },
      { type: 'income', bonus: { conservation: 1 } },
      { type: 'bonus', bonus: { FullThroated: 1 } },
      { type: 'bonus', bonus: { money: 12 } },
      { type: 'bonus', bonus: { xtoken: 3 } },
    ],
    lastWorkerBonus: { conservation: 2 },
    partnerZooBonuses: { 2: { 'upgrade-card': 1 }, 3: { 'add-worker': 1 }, 4: { conservation: 2 } },
    facBonuses: { 2: { 'upgrade-card': 1 }, 3: { conservation: 2 } },
  },
  1: {
    id: '1',
    name: 'Observation Tower',
    terrains: {
      Water: ['4_5', '5_6', '5_12', '6_7', '7_6', '8_5', '8_7'],
      Rock: ['0_5', '0_7', '0_9', '1_0', '1_6', '2_1', '3_0', '3_10', '3_12'],
    },
    upgradeNeeded: ['3_4', '4_7', '5_8'],
    bonuses: {
      '0_1': { xtoken: 1 },
      '0_11': { money: 5 },
      '3_6': { 'take-in-range': 1 },
      '4_1': { Clever: 1 },
      '4_11': { reputation: 1 },
      '6_5': { money: 5 },
      '7_2': { 'take-in-range': 1 },
      '7_8': { xtoken: 1 },
      '4_13': { xtoken: 1 },
    },
    bonusSpaces: [
      { type: 'income', bonus: { Snapping: 1 } },
      { type: 'income', bonus: { 'enclosure-size-2': 1 } },
      { type: 'income', bonus: { money: 5 } },
      { type: 'income', bonus: { 'bonus-sponsor': 1 } },
      { type: 'bonus', bonus: { FullThroated: 1 } },
      { type: 'bonus', bonus: { money: 12 } },
      { type: 'bonus', bonus: { xtoken: 3 } },
    ],
    lastWorkerBonus: null,
    partnerZooBonuses: { 2: { 'upgrade-card': 1 }, 3: { 'add-worker': 1 }, 4: { conservation: 2 } },
    facBonuses: { 2: { 'upgrade-card': 1 }, 3: { conservation: 1 } },
  },
  2: {
    id: '2',
    name: 'Outdoor Areas',
    terrains: {
      Water: ['3_8', '4_9', '4_11', '5_8', '5_10', '6_1', '7_0'],
      Rock: ['0_1', '0_3', '0_9', '0_11', '1_4', '1_10', '4_1', '5_0', '8_5'],
    },
    upgradeNeeded: ['1_0', '2_1', '3_6', '5_6'],
    bonuses: {
      '0_5': { reputation: 1 },
      '1_2': { 'Partner-Zoo': 1 },
      '1_12': { 'bonus-sponsor': 1 },
      '4_7': { xtoken: 1 },
      '5_2': { 'take-in-range': 1 },
      '7_2': { 'take-in-range': 1 },
      '7_6': { xtoken: 1 },
      '8_11': { Clever: 1 },
    },
    bonusSpaces: [
      { type: 'income', bonus: { Snapping: 1 } },
      { type: 'income', bonus: { 'enclosure-size-2': 1 } },
      { type: 'income', bonus: { money: 5 } },
      { type: 'bonus', bonus: { conservation: 1 } },
      { type: 'bonus', bonus: { FullThroated: 1 } },
      { type: 'bonus', bonus: { money: 12 } },
      { type: 'bonus', bonus: { xtoken: 3 } },
    ],
    lastWorkerBonus: { conservation: 1 },
    partnerZooBonuses: { 2: { 'upgrade-card': 1 }, 3: { 'add-worker': 1 } },
    facBonuses: { 2: { 'upgrade-card': 1 }, 3: { conservation: 2 } },
  },
  3: {
    id: '3',
    name: 'Silver Lake',
    terrains: {
      Water: ['0_11', '1_6', '2_3', '2_5', '2_7', '5_10', '5_12', '6_1', '6_9'],
      Rock: ['3_12', '4_11', '5_0', '6_3', '7_0', '8_5', '8_7'],
    },
    upgradeNeeded: ['0_1', '1_0', '1_2', '1_4', '2_1'],
    bonuses: {
      '0_5': { money: 2 },
      '0_7': { money: 2 },
      '1_2': { money: 2 },
      '1_4': { money: 2 },
      '1_8': { money: 2 },
      '2_1': { money: 2 },
      '2_9': { money: 2 },
      '3_2': { money: 2 },
      '3_4': { money: 2 },
      '3_6': { money: 2 },
      '3_8': { money: 2 },
      '0_3': { reputation: 1 },
      '1_12': { 'take-in-range': 1 },
      '4_9': { reputation: 1 },
      '5_2': { Clever: 1 },
      '5_6': { 'take-in-range': 1 },
      '6_11': { xtoken: 1 },
      '7_2': { 'bonus-sponsor': 1 },
      '8_9': { xtoken: 1 },
    },
    bonusSpaces: [
      { type: 'income', bonus: { Snapping: 1 } },
      { type: 'income', bonus: { 'enclosure-size-2': 1 } },
      { type: 'income', bonus: { money: 5 } },
      { type: 'bonus', bonus: { Determination: 1 } },
      { type: 'bonus', bonus: { FullThroated: 1 } },
      { type: 'bonus', bonus: { money: 12 } },
      { type: 'bonus', bonus: { xtoken: 3 } },
    ],
    lastWorkerBonus: null,
    partnerZooBonuses: { 2: { 'upgrade-card': 1 }, 3: { 'add-worker': 1 }, 4: { conservation: 1 } },
    facBonuses: { 2: { 'upgrade-card': 1 }, 3: { conservation: 2 } },
  },
  4: {
    id: '4',
    name: 'Commercial Harbor',
    terrains: {
      Water: ['0_9', '1_4', '1_12', '2_3', '2_5', '3_4', '5_0', '8_1', '8_3'],
      Rock: ['3_8', '3_10', '5_12', '6_5', '6_7', '7_2', '7_10'],
    },
    upgradeNeeded: ['6_3', '8_5', '8_7', '8_9'],
    bonuses: {
      '0_5': { reputation: 1 },
      '1_2': { xtoken: 1 },
      '2_9': { Clever: 1 },
      '3_2': { xtoken: 1 },
      '3_6': { 'take-in-range': 1 },
      '5_4': { xtoken: 1 },
      '6_1': { 'take-in-range': 1 },
      '7_4': { Multiplier: 1 },
      '8_11': { money: 5 },
    },
    bonusSpaces: [
      { type: 'income', bonus: { Snapping: 1 } },
      { type: 'income', bonus: { 'enclosure-size-2': 1 } },
      { type: 'income', bonus: { money: 5 } },
      { type: 'bonus', bonus: { Fac: 1 } },
      { type: 'bonus', bonus: { FullThroated: 1 } },
      { type: 'bonus', bonus: { money: 12 } },
      { type: 'bonus', bonus: { xtoken: 3 } },
    ],
    lastWorkerBonus: { conservation: 1 },
    partnerZooBonuses: { 2: { 'upgrade-card': 1 }, 3: { 'add-worker': 1 }, 4: { conservation: 1 } },
    facBonuses: { 2: { 'upgrade-card': 1 }, 3: { conservation: 1 } },
  },
  5: {
    id: '5',
    name: 'Park Restaurant',
    terrains: {
      Water: ['0_5', '1_4', '2_9', '4_3', '5_8', '5_10', '7_6', '8_7'],
      Rock: ['1_8', '2_3', '2_5', '4_5', '6_1', '6_9', '7_4'],
    },
    upgradeNeeded: ['1_2', '1_10', '5_12'],
    bonuses: {
      '1_0': { xtoken: 1 },
      '1_6': { xtoken: 1 },
      '2_7': { 'bonus-sponsor': 1 },
      '4_1': { Clever: 1 },
      '4_9': { 'take-in-range': 1 },
      '6_3': { 'take-in-range': 1 },
      '6_7': { 'take-in-range': 1 },
      '6_11': { money: 5 },
      '8_3': { reputation: 1 },
    },
    bonusSpaces: [
      { type: 'income', bonus: { Snapping: 1 } },
      { type: 'income', bonus: { 'enclosure-size-2': 1 } },
      { type: 'income', bonus: { money: 5 } },
      { type: 'bonus', bonus: { 'special-enclosures': 1 } },
      { type: 'bonus', bonus: { FullThroated: 1 } },
      { type: 'bonus', bonus: { money: 12 } },
      { type: 'bonus', bonus: { xtoken: 3 } },
    ],
    lastWorkerBonus: { conservation: 1 },
    partnerZooBonuses: { 2: { 'upgrade-card': 1 }, 3: { 'add-worker': 1 }, 4: { conservation: 2 } },
    facBonuses: { 2: { 'upgrade-card': 1 } },
  },
  6: {
    id: '6',
    name: 'Research Institute',
    terrains: {
      Water: ['0_1', '0_3', '5_10', '5_12', '7_4', '7_6', '8_1', '8_3', '8_11'],
      Rock: ['2_7', '2_9', '3_6', '3_8', '4_1', '5_0', '7_10'],
    },
    upgradeNeeded: ['4_3', '5_4', '6_1', '7_0'],
    bonuses: {
      '1_2': { xtoken: 1 },
      '1_8': { Clever: 1 },
      '2_5': { money: 5 },
      '3_0': { xtoken: 1 },
      '3_10': { 'take-in-range': 1 },
      '5_2': { 'take-in-range': 1 },
      '6_11': { reputation: 1 },
      '7_2': { Fac: 1 },
      '8_7': { money: 5 },
    },
    bonusSpaces: [
      { type: 'income', bonus: { Snapping: 1 } },
      { type: 'income', bonus: { 'enclosure-size-2': 1 } },
      { type: 'income', bonus: { money: 5 } },
      { type: 'income', bonus: { Clever: 2 } },
      { type: 'bonus', bonus: { FullThroated: 1 } },
      { type: 'bonus', bonus: { money: 12 } },
      { type: 'bonus', bonus: { xtoken: 3 } },
    ],
    lastWorkerBonus: { conservation: 2 },
    partnerZooBonuses: { 2: { 'upgrade-card': 1 }, 3: { 'add-worker': 1 }, 4: { conservation: 1 } },
    facBonuses: { 2: { 'upgrade-card': 1 } },
  },
  7: {
    id: '7',
    name: 'Ice Cream Parlors',
    terrains: {
      Water: ['7_0', '7_4', '7_10', '8_1', '8_3', '8_5', '8_11'],
      Rock: ['0_1', '0_3', '1_8', '2_9', '3_4', '4_1', '4_3', '4_9', '5_8'],
    },
    upgradeNeeded: ['3_8', '3_10', '3_12'],
    bonuses: {
      '0_5': { reputation: 1 },
      '1_2': { kiosk: 1 },
      '1_10': { reputation: 1 },
      '3_2': { 'take-in-range': 1 },
      '3_6': { 'bonus-sponsor': 1 },
      '4_7': { 'take-in-range': 1 },
      '4_11': { 'take-in-range': 1 },
      '5_4': { kiosk: 1 },
      '5_10': { kiosk: 1 },
      '7_2': { xtoken: 1 },
      '7_6': { Clever: 1 },
      '7_12': { money: 5 },
      '8_9': { xtoken: 1 },
    },
    bonusSpaces: [
      { type: 'income', bonus: { Snapping: 1 } },
      { type: 'income', bonus: { 'enclosure-size-2': 1 } },
      { type: 'income', bonus: { money: 5 } },
      { type: 'income', bonus: { Pouch: 2 } },
      { type: 'bonus', bonus: { FullThroated: 1 } },
      { type: 'bonus', bonus: { money: 12 } },
      { type: 'bonus', bonus: { xtoken: 3 } },
    ],
    lastWorkerBonus: { conservation: 2 },
    partnerZooBonuses: { 2: { 'upgrade-card': 1 }, 3: { 'add-worker': 1 } },
    facBonuses: { 2: { 'upgrade-card': 1 }, 3: { conservation: 1 } },
  },
  8: {
    id: '8',
    name: 'Hollywood Hills',
    terrains: {
      Water: ['1_0', '1_4', '2_5', '4_3', '5_2', '5_4', '6_3'],
      Rock: ['0_9', '0_11', '1_12', '2_11', '3_12', '4_9', '5_12', '6_11', '7_10'],
    },
    upgradeNeeded: ['2_7', '3_6', '3_10'],
    bonuses: {
      '0_7': { Clever: 1 },
      '1_2': { xtoken: 1 },
      '3_0': { xtoken: 1 },
      '4_5': { xtoken: 1 },
      '6_1': { money: 5 },
      '7_4': { 'take-in-range': 1 },
      '8_9': { reputation: 1 },
    },
    bonusSpaces: [
      { type: 'income', bonus: { Snapping: 1 } },
      { type: 'income', bonus: { 'enclosure-size-2': 1 } },
      { type: 'income', bonus: { money: 5 } },
      { type: 'bonus', bonus: { 'Partner-Zoo': 1 } },
      { type: 'bonus', bonus: { FullThroated: 1 } },
      { type: 'bonus', bonus: { money: 12 } },
      { type: 'bonus', bonus: { xtoken: 3 } },
    ],
    lastWorkerBonus: { conservation: 1 },
    partnerZooBonuses: { 2: { 'upgrade-card': 1 }, 3: { 'add-worker': 1 }, 4: { conservation: 1 } },
    facBonuses: { 2: { 'upgrade-card': 1 }, 3: { conservation: 1 } },
  },
};
