const PLANETS_DATA = [
  {
    id: '0',
    name: 'KSB-4156',
    desc: 'Score medals for every complete row and column.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'ice', 'land', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'ice', 'ice', 'land', 'lifepod', 'ice', 'land', 'nothing', 'nothing'],
      ['nothing', 'land', 'land', 'land', 'land', 'ice', 'land', 'land', 'ice', 'ice', 'land', 'nothing'],
      ['nothing', 'lifepod', 'land', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'lifepod', 'nothing'],
      ['ice', 'ice', 'land', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'land', 'land'],
      ['ice', 'ice', 'land', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'land', 'land'],
      ['nothing', 'land', 'lifepod', 'land', 'ice', 'ice', 'land', 'land', 'land', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'ice', 'ice', 'land', 'land', 'land', 'lifepod', 'land', 'land', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'land', 'lifepod', 'land', 'land', 'land', 'land', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'ice', 'land', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
  {
    id: '1',
    name: 'Arashi',
    desc: "Every Tile placed onto the planet's ring must also be anchored outside the ring.",
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'land', 'ice', 'ice', 'ice', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'lifepod', 'land', 'land', 'land', 'land', 'land', 'land', 'lifepod', 'nothing', 'nothing'],
      ['nothing', 'land', 'land', 'ice', 'ice', 'ice', 'land', 'ice', 'ice', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'land', 'land', 'lifepod', 'land', 'ice', 'land', 'land', 'land', 'nothing'],
      ['ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring'],
      ['ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring'],
      ['nothing', 'ice', 'ice', 'ice', 'land', 'land', 'lifepod', 'ice', 'ice', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'land', 'ice', 'land', 'land', 'ice', 'ice', 'land', 'land', 'nothing'],
      ['nothing', 'nothing', 'lifepod', 'land', 'land', 'land', 'land', 'land', 'land', 'lifepod', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'land', 'ice', 'ice', 'ice', 'ice', 'land', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
  {
    id: '2',
    name: 'Cerberus',
    desc: 'Gain a bonus 2 medals for each planet your tiles cover completely.',
    terrains: [
      ['nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'land', 'land', 'land', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'land', 'land', 'ice', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'lifepod', 'ice', 'ice', 'ice', 'land'],
      ['nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'ice', 'ice', 'land', 'land', 'land'],
      ['nothing', 'nothing', 'land', 'land', 'land', 'nothing', 'nothing', 'ice', 'land', 'land', 'lifepod', 'nothing'],
      ['nothing', 'land', 'lifepod', 'land', 'land', 'land', 'land', 'ice', 'ice', 'ice', 'land', 'nothing'],
      ['land', 'land', 'land', 'land', 'land', 'land', 'ice', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing'],
      ['land', 'land', 'ice', 'ice', 'ice', 'ice', 'ice', 'nothing', 'land', 'land', 'ice', 'nothing'],
      ['land', 'ice', 'ice', 'land', 'land', 'ice', 'lifepod', 'land', 'land', 'land', 'ice', 'land'],
      ['land', 'ice', 'land', 'lifepod', 'land', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'land'],
      ['nothing', 'land', 'land', 'land', 'land', 'land', 'land', 'land', 'lifepod', 'land', 'ice', 'land'],
      ['nothing', 'nothing', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'land', 'land', 'land', 'nothing'],
    ],
    columnMedals: [1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1],
    rowMedals: [1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1],
  },
  {
    id: '3',
    name: 'Charybdis',
    desc: 'First tile placement must cover one of the central four squares.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'land', 'lifepod', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'ice', 'ice', 'land', 'land', 'ice', 'lifepod', 'nothing', 'nothing'],
      ['nothing', 'land', 'land', 'land', 'lifepod', 'ice', 'land', 'land', 'ice', 'ice', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'land', 'ice', 'ice', 'ice', 'ice', 'ice', 'lifepod', 'land', 'nothing'],
      ['ice', 'land', 'land', 'land', 'ice', 'hole', 'hole', 'ice', 'land', 'land', 'land', 'land'],
      ['ice', 'land', 'land', 'land', 'ice', 'hole', 'hole', 'ice', 'land', 'land', 'land', 'land'],
      ['nothing', 'land', 'land', 'land', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'ice', 'ice', 'lifepod', 'land', 'lifepod', 'ice', 'ice', 'land', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'land', 'land', 'land', 'land', 'land', 'land', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'land', 'land', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'ice',
        'ice',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
  {
    id: '4',
    name: 'Gaia',
    desc: 'Every city not covered by tiles scores two medals. Score complete rows and columns as normal.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'city',
        'lifepod',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'ice', 'land', 'land', 'land', 'land', 'ice', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'city', 'lifepod', 'ice', 'land', 'land', 'ice', 'land', 'city', 'nothing', 'nothing'],
      ['nothing', 'land', 'land', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'ice', 'lifepod', 'land', 'land', 'land', 'ice', 'land', 'land', 'nothing'],
      ['land', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'ice', 'land', 'land', 'city'],
      ['city', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'ice', 'land', 'land', 'land'],
      ['nothing', 'land', 'land', 'ice', 'land', 'land', 'land', 'lifepod', 'ice', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'lifepod', 'land', 'nothing'],
      ['nothing', 'nothing', 'city', 'land', 'land', 'land', 'land', 'land', 'land', 'city', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'land', 'land', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'lifepod',
        'city',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
  {
    id: '5',
    name: 'K-273',
    desc: 'You may not place a tile that overlaps both planet terrain and planet ice.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'ice',
        'ice',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'ice', 'ice', 'lifepod', 'ice', 'ice', 'ice', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'nothing', 'nothing'],
      ['nothing', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'land', 'lifepod', 'ice', 'ice', 'nothing'],
      ['nothing', 'ice', 'ice', 'lifepod', 'ice', 'ice', 'ice', 'ice', 'land', 'ice', 'ice', 'nothing'],
      ['ice', 'ice', 'land', 'land', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice'],
      ['ice', 'ice', 'lifepod', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'land', 'lifepod'],
      ['nothing', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'land', 'nothing'],
      ['nothing', 'ice', 'ice', 'ice', 'ice', 'land', 'land', 'ice', 'ice', 'ice', 'land', 'nothing'],
      ['nothing', 'nothing', 'ice', 'ice', 'ice', 'lifepod', 'land', 'ice', 'ice', 'ice', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'ice',
        'ice',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
  {
    id: '6',
    name: "K'Aax",
    desc: 'Your rover may not move onto toxic terrain. You may place tiles over toxic terrain to neutralize it.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'toxic', 'land', 'land', 'land', 'ice', 'ice', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'toxic', 'toxic', 'toxic', 'land', 'land', 'land', 'ice', 'lifepod', 'nothing', 'nothing'],
      ['nothing', 'ice', 'ice', 'toxic', 'lifepod', 'toxic', 'land', 'toxic', 'toxic', 'land', 'land', 'nothing'],
      ['nothing', 'ice', 'land', 'land', 'toxic', 'land', 'toxic', 'toxic', 'land', 'land', 'land', 'nothing'],
      ['lifepod', 'toxic', 'land', 'land', 'land', 'land', 'land', 'land', 'land', 'land', 'land', 'lifepod'],
      ['land', 'toxic', 'land', 'ice', 'ice', 'ice', 'land', 'land', 'ice', 'ice', 'ice', 'land'],
      ['nothing', 'land', 'ice', 'ice', 'toxic', 'ice', 'land', 'land', 'ice', 'toxic', 'toxic', 'nothing'],
      ['nothing', 'land', 'ice', 'toxic', 'ice', 'ice', 'land', 'land', 'ice', 'toxic', 'lifepod', 'nothing'],
      ['nothing', 'nothing', 'toxic', 'toxic', 'ice', 'land', 'land', 'ice', 'ice', 'toxic', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'land', 'ice', 'lifepod', 'land', 'ice', 'land', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
  {
    id: '7',
    name: 'Lacuna',
    desc: 'You may not place tiles covering the holes of the planet.',
    terrains: [
      ['nothing', 'nothing', 'nothing', 'nothing', 'land', 'ice', 'land', 'land', 'nothing', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'ice', 'ice', 'land', 'land', 'land', 'land', 'nothing', 'nothing'],
      ['nothing', 'land', 'ice', 'ice', 'land', 'nothing', 'nothing', 'land', 'land', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'ice', 'lifepod', 'nothing', 'land', 'land', 'nothing', 'land', 'land', 'land', 'nothing'],
      ['land', 'land', 'ice', 'ice', 'nothing', 'nothing', 'land', 'lifepod', 'ice', 'ice', 'ice', 'ice'],
      ['land', 'lifepod', 'land', 'ice', 'ice', 'land', 'land', 'land', 'ice', 'nothing', 'nothing', 'land'],
      ['land', 'land', 'nothing', 'land', 'ice', 'ice', 'nothing', 'land', 'ice', 'land', 'lifepod', 'land'],
      ['land', 'land', 'land', 'nothing', 'land', 'ice', 'ice', 'ice', 'ice', 'land', 'nothing', 'land'],
      ['nothing', 'land', 'land', 'nothing', 'land', 'land', 'ice', 'nothing', 'lifepod', 'land', 'land', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'land', 'lifepod', 'land', 'ice', 'land', 'land', 'nothing', 'land', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'land', 'land', 'ice', 'ice', 'land', 'land', 'land', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'nothing', 'land', 'ice', 'land', 'land', 'nothing', 'nothing', 'nothing', 'nothing'],
    ],
    columnMedals: [1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1],
    rowMedals: [1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1],
  },
  {
    id: '8',
    name: 'Oblivion',
    desc: 'Ice has amassed in the corners',
    terrains: [
      ['ice', 'ice', 'ice', 'land', 'land', 'land', 'land', 'land', 'land', 'ice', 'ice', 'ice'],
      ['ice', 'ice', 'ice', 'land', 'land', 'land', 'lifepod', 'land', 'land', 'ice', 'ice', 'ice'],
      ['ice', 'ice', 'ice', 'land', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'ice', 'ice', 'ice'],
      ['lifepod', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'lifepod', 'land', 'land'],
      ['land', 'land', 'land', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'land', 'land'],
      [
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
      ],
      [
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
      ],
      ['land', 'land', 'land', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'land', 'land'],
      ['land', 'land', 'lifepod', 'land', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'land', 'land', 'lifepod'],
      ['ice', 'ice', 'ice', 'land', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'ice', 'ice', 'ice'],
      ['ice', 'ice', 'ice', 'land', 'lifepod', 'land', 'land', 'land', 'land', 'ice', 'ice', 'ice'],
      ['ice', 'ice', 'ice', 'land', 'land', 'land', 'land', 'land', 'land', 'ice', 'ice', 'ice'],
    ],
    columnMedals: [3, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 3],
    rowMedals: [3, 3, 1, 1, 1, 0, 0, 1, 1, 1, 3, 3],
  },
  {
    id: '9',
    name: 'Pajitnov',
    desc: 'You must be able to slide your tiles into place.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'ice', 'ice', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'land', 'land', 'land', 'ice', 'ice', 'lifepod', 'nothing', 'nothing'],
      ['nothing', 'land', 'lifepod', 'ice', 'land', 'land', 'land', 'land', 'ice', 'ice', 'land', 'nothing'],
      ['nothing', 'ice', 'land', 'land', 'ice', 'ice', 'land', 'land', 'lifepod', 'land', 'land', 'nothing'],
      ['land', 'ice', 'ice', 'land', 'ice', 'ice', 'land', 'ice', 'land', 'land', 'land', 'land'],
      ['land', 'land', 'ice', 'land', 'land', 'land', 'land', 'ice', 'land', 'land', 'land', 'land'],
      ['nothing', 'land', 'lifepod', 'ice', 'land', 'land', 'land', 'ice', 'ice', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'lifepod', 'land', 'land', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'land', 'land', 'land', 'ice', 'ice', 'ice', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'ice', 'land', 'land', 'lifepod', 'land', 'ice', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
  {
    id: '10',
    name: 'Persephone',
    desc: 'Each quadrant has one restricted resource. Do not place a restricted resource in the quadrant.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'ice', 'land', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'ice', 'ice', 'ice', 'ice', 'land', 'land', 'land', 'land', 'nothing', 'nothing'],
      ['nothing', 'land', 'ice', 'land', 'lifepod', 'ice', 'land', 'land', 'land', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'ice', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'lifepod', 'nothing'],
      ['land', 'lifepod', 'ice', 'land', 'land', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice'],
      ['land', 'land', 'ice', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'land', 'land'],
      ['nothing', 'land', 'ice', 'lifepod', 'ice', 'ice', 'land', 'land', 'land', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'ice', 'ice', 'ice', 'land', 'land', 'land', 'land', 'land', 'land', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'land', 'land', 'land', 'land', 'land', 'lifepod', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'ice', 'lifepod', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
  {
    id: '11',
    name: 'Petra',
    desc: 'You may treat the electrical currents as energy terrain. There is no Ice.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'land', 'electric', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'land',
        'lifepod',
        'electric',
        'electric',
        'land',
        'land',
        'lifepod',
        'electric',
        'nothing',
        'nothing',
      ],
      ['nothing', 'land', 'land', 'land', 'land', 'electric', 'land', 'electric', 'electric', 'electric', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'land', 'land', 'electric', 'land', 'electric', 'land', 'land', 'land', 'nothing'],
      [
        'land',
        'land',
        'electric',
        'electric',
        'electric',
        'electric',
        'land',
        'electric',
        'electric',
        'electric',
        'land',
        'land',
      ],
      ['land', 'electric', 'electric', 'land', 'lifepod', 'electric', 'land', 'electric', 'lifepod', 'electric', 'land', 'land'],
      [
        'nothing',
        'electric',
        'land',
        'land',
        'electric',
        'electric',
        'electric',
        'electric',
        'electric',
        'electric',
        'land',
        'nothing',
      ],
      ['nothing', 'electric', 'electric', 'electric', 'electric', 'land', 'land', 'electric', 'land', 'land', 'land', 'nothing'],
      [
        'nothing',
        'nothing',
        'land',
        'lifepod',
        'land',
        'land',
        'land',
        'electric',
        'electric_lifepod',
        'land',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'land', 'land', 'land', 'land', 'land', 'electric', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
  {
    id: '12',
    name: 'Tartarus',
    desc: 'Tiles may not be placed covering the chasm. Rovers may not move across the chasm with orthogonal movement.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'lifepod',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'ice', 'land', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'land', 'land', 'land', 'land', 'ice', 'ice', 'nothing', 'nothing'],
      ['nothing', 'lifepod', 'ice', 'ice', 'land', 'land', 'land', 'ice', 'ice', 'ice', 'land', 'nothing'],
      ['nothing', 'land', 'ice', 'land', 'land', 'ice', 'lifepod', 'ice', 'land', 'land', 'land', 'nothing'],
      ['land', 'ice', 'ice', 'land', 'land', 'ice', 'ice', 'ice', 'land', 'land', 'land', 'land'],
      ['ice', 'ice', 'land', 'land', 'land', 'ice', 'lifepod', 'ice', 'land', 'land', 'land', 'land'],
      ['nothing', 'land', 'land', 'land', 'land', 'land', 'land', 'ice', 'land', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'land', 'land', 'land', 'land', 'ice', 'land', 'land', 'lifepod', 'nothing'],
      ['nothing', 'nothing', 'land', 'land', 'land', 'land', 'lifepod', 'land', 'land', 'land', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'land', 'land', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    sides: [
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
      [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
      [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
      [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
      [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
      [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
      [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
      [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
      [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
      [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
      [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
];
const CORPOS_DATA = [
  {
    id: '0',
    name: 'Universal Coalition',
    desc: 'Advance your trackers to gain benefits, \n    unlock milestones, and score the highest medal your tracker covers or surpasses',
    tracks: {
      civ: [null, null, 1, 'civ', null, 2, 'civ', null, 'Synergy', 3, 'civ', 'Synergy', null, null, 'civ', 5],
      water: [null, null, 1, 'Synergy', 2, null, 3, 'Synergy', 4, null, 5, null, 'Synergy', 7, null, 10],
      biomass: [
        null,
        null,
        'Synergy',
        'biomass',
        null,
        1,
        'biomass',
        null,
        2,
        'biomass',
        'Synergy',
        'biomass',
        3,
        'biomass',
        null,
        5,
      ],
      rover: [
        null,
        'rover',
        'move_1',
        'move_1',
        'move_2',
        'move_2',
        ['move_2', 'rover'],
        'move_2',
        ['move_2', 1],
        'move_3',
        ['move_3', 'Synergy'],
        'move_3',
        ['move_3', 2],
        'move_4',
        'move_4',
        ['move_4', 5],
      ],
      tech: [null, null, 'Synergy', 'tech', null, 'tech', 1, 'tech', null, null, 'tech', null, 'Synergy', 2, 'tech', 5],
    },
  },
  {
    id: '1',
    name: 'Cosmos inc',
    desc: 'Choose to position a collected lifepod onto your advancement track or onto your scoring area. Your trackers skip over lifepods when advancing. Benefits and medals covered by lifepods are ignored.',
    tracks: {
      civ: [null, null, 1, 'civ', null, 2, 'civ', null, 'Synergy', 3, 'civ', 'Synergy', null, null, 'civ', 5],
      water: [null, null, 1, 'Synergy', 2, null, 3, 'Synergy', 4, null, 5, null, 'Synergy', 7, null, 10],
      biomass: [
        null,
        null,
        'Synergy',
        'biomass',
        null,
        1,
        'biomass',
        null,
        2,
        'biomass',
        'Synergy',
        'biomass',
        3,
        'biomass',
        null,
        5,
      ],
      rover: [
        null,
        'rover',
        'move_1',
        'move_1',
        'move_2',
        'move_2',
        'move_2',
        'move_2',
        ['move_2', 1],
        'move_2',
        ['move_2', 'Synergy'],
        'move_2',
        ['move_2', 2],
        'move_3',
        'move_3',
        ['move_3', 5],
      ],
      tech: [null, null, 'Synergy', 'tech', null, 'tech', 1, 'tech', null, null, 'tech', null, 'Synergy', 2, 'tech', 5],
    },
  },
  {
    id: '2',
    name: 'Flux Industries',
    desc: 'Your flux token designates on of your resource tracks as the flux track. Whenever you unlock a tech, you may reposition your flux token. Only your most recently unlocked teck is available.',
    tracks: {
      civ: [null, null, 1, 'civ', null, 2, 'civ', null, 'Synergy', 3, 'civ', 'Synergy', null, null, 'civ', 5],
      water: [null, null, 1, 'Synergy', 2, null, 3, 'Synergy', 4, null, 5, null, 'Synergy', 7, null, 10],
      biomass: [
        null,
        null,
        'Synergy',
        'biomass',
        null,
        1,
        'biomass',
        null,
        2,
        'biomass',
        'Synergy',
        'biomass',
        3,
        'biomass',
        null,
        5,
      ],
      rover: [
        null,
        'rover',
        'move_1',
        'move_1',
        'move_2',
        'move_2',
        ['move_2', 'rover'],
        'move_2',
        ['move_2', 1],
        'move_2',
        ['move_2', 'Synergy'],
        'move_2',
        ['move_2', 2],
        'move_3',
        'move_3',
        ['move_3', 5],
      ],
      tech: [null, null, 'Synergy', 'tech', null, 'tech', 1, 'tech', null, null, 'tech', null, 'Synergy', 2, 'tech', 5],
    },
  },
  {
    id: '3',
    name: 'Horizon Group',
    desc: 'To Collect meteorite, your rover must pick it up and deliver it to a rover resource on your planet.',
    tracks: {
      civ: [null, null, 1, 'civ', null, 2, 'civ', null, 'Synergy', 3, 'civ', 'Synergy', null, null, 'civ', 5],
      water: [null, null, 1, 'Synergy', 2, null, 3, 'Synergy', 4, null, 5, null, 'Synergy', 7, null, 10],
      biomass: [
        null,
        null,
        'Synergy',
        'biomass',
        null,
        1,
        'biomass',
        null,
        2,
        'biomass',
        'Synergy',
        'biomass',
        3,
        'biomass',
        null,
        5,
      ],
      rover: [
        null,
        'rover',
        'move_2',
        ['move_2', 'rover'],
        'move_2',
        'move_3',
        ['move_3', 'rover'],
        'move_3',
        ['move_4', 1],
        ['move_4', 'rover'],
        ['move_4', 'Synergy'],
        'move_4',
        ['move_5', 2],
        'move_5',
        'move_5',
        ['move_5', 5],
      ],
      tech: [null, null, 'Synergy', 'tech', null, 'tech', 1, 'tech', null, null, 'tech', null, 'Synergy', 2, 'tech', 5],
    },
  },
  {
    id: '4',
    name: 'Jump Drive',
    desc: 'Choose to place a collected lifepod onto your tech or your scoring area. A lifepod placed onto tech unlocks the tech in any order.',
    tracks: {
      civ: [null, null, 1, 'civ', null, 2, 'civ', null, 'Synergy', 3, 'civ', 'Synergy', null, null, 'civ', 5],
      water: [null, null, 1, 'Synergy', 2, null, 3, 'Synergy', 4, null, 5, null, 'Synergy', 7, null, 10],
      biomass: [
        null,
        null,
        'Synergy',
        'biomass',
        null,
        1,
        'biomass',
        null,
        2,
        'biomass',
        'Synergy',
        'biomass',
        3,
        'biomass',
        null,
        5,
      ],
      rover: [
        null,
        'rover',
        'move_1',
        'move_1',
        'move_2',
        'move_2',
        'move_2',
        'move_2',
        ['move_2', 1],
        'move_2',
        ['move_2', 'Synergy'],
        'move_2',
        ['move_2', 2],
        'move_3',
        'move_3',
        ['move_3', 5],
      ],
      tech: [null, 5, 'Synergy', null, null, null, 3, null, 2, null, null, 1, 'Synergy', null, null, null],
    },
  },
  {
    id: '5',
    name: 'Make Shift',
    desc: 'You may advance any tracker diagonally onto an adjacent track. Any tracker may claim any benefit. Tech Levels are locked if no tracker is currently unlocking the tech.',
    tracks: {
      civ: [null, null, 1, 'civ', null, 2, 'civ', null, 'Synergy', 3, 'civ', 'Synergy', null, null, 'civ', 5],
      water: [null, null, 1, 'Synergy', 2, null, 'Synergy', 3, 'Synergy', null, null, 4, 'Synergy', null, null, 5],
      biomass: [
        null,
        null,
        'Synergy',
        'biomass',
        null,
        1,
        'biomass',
        null,
        2,
        'biomass',
        'Synergy',
        'biomass',
        3,
        'biomass',
        null,
        5,
      ],
      rover: [
        null,
        'rover',
        'move_1',
        'move_1',
        'move_2',
        'move_2',
        ['move_2', 'rover'],
        'move_2',
        ['move_2', 'Synergy'],
        'move_2',
        ['move_2', 1],
        'move_2',
        ['move_2', 2],
        'move_3',
        'move_3',
        ['move_3', 5],
      ],
      tech: [null, null, 'Synergy', 'tech', null, 'tech', 1, 'tech', null, null, 'tech', null, 'Synergy', 2, 'tech', 5],
    },
  },
  {
    id: '6',
    name: 'Oasis Ultd.',
    desc: 'Advance your water tracker once for each water terrain square that covers planet ice. Gain the benefits from advancing your water tracker even when it advances onto another track.',
    tracks: {
      civ: [null, null, 1, 'civ', null, 2, 'civ', null, 'Synergy', 3, 'civ', 'Synergy', null, null, 'civ', 5],
      water: [null, null, 'skip', 'Synergy', 'skip', 'Synergy', 3, 'skip', 'skip', 5, 'skip', 8, 'skip', 12, null, 15],
      biomass: [
        null,
        null,
        'Synergy',
        'biomass',
        null,
        1,
        'biomass',
        null,
        2,
        'biomass',
        'Synergy',
        'biomass',
        3,
        'biomass',
        null,
        5,
      ],
      rover: [
        null,
        'rover',
        'move_1',
        'move_1',
        'move_2',
        'move_2',
        ['move_2', 'rover'],
        'move_2',
        ['move_2', 1],
        'move_2',
        ['move_2', 'Synergy'],
        'move_2',
        ['move_2', 2],
        'move_3',
        'move_3',
        ['move_3', 5],
      ],
      tech: [null, null, 'Synergy', 'tech', null, 'tech', 1, 'tech', null, null, 'tech', null, 'Synergy', 2, 'tech', 5],
    },
  },
  {
    id: '7',
    name: 'Republic',
    desc: 'You must regress another tracker each time you claim a milestone from the civ track. Do not claim benefits from regressing.',
    tracks: {
      civ: [null, null, 'civ', null, 'civ', null, 'civ', null, 'civ', null, 'civ', null, 'civ', null, 'civ', 5],
      water: [null, null, 1, 'Synergy', 2, null, 3, 'Synergy', 4, null, 5, null, 'Synergy', 7, null, 10],
      biomass: [
        null,
        null,
        'Synergy',
        'biomass',
        null,
        1,
        'biomass',
        null,
        2,
        'biomass',
        'Synergy',
        'biomass',
        3,
        'biomass',
        null,
        5,
      ],
      rover: [
        null,
        'rover',
        'move_1',
        'move_1',
        'move_2',
        'move_2',
        'move_2',
        'move_2',
        ['move_2', 1],
        'move_2',
        ['move_2', 'Synergy'],
        'move_2',
        ['move_2', 2],
        'move_3',
        'move_3',
        ['move_3', 5],
      ],
      tech: [null, null, 'Synergy', 'tech', null, 'tech', 1, 'tech', null, null, 'tech', null, 'Synergy', 2, 'tech', 5],
    },
  },
  {
    id: '8',
    name: 'Wormhole Corp',
    desc: 'Advance your biomass tracker from tile placement only when you expand a biomass terrain area.',
    tracks: {
      civ: [null, null, 1, 'civ', null, 2, 'civ', null, 'Synergy', 3, 'civ', 'Synergy', null, null, 'civ', 5],
      water: [null, null, 1, 'Synergy', 2, null, 3, 'Synergy', 4, null, 5, null, 'Synergy', 7, null, 10],
      biomass: [
        null,
        'skip',
        'Synergy',
        'biomass',
        ['skip', 1],
        'synergy_civ',
        'biomass',
        ['skip', 2],
        'synergy_water',
        'biomass',
        ['skip', 3],
        'synergy_tech',
        'biomass',
        ['skip', 5],
        'synergy_rover',
        'biomass',
      ],
      rover: [
        null,
        'rover',
        'move_1',
        'move_1',
        'move_2',
        'move_2',
        ['move_2', 'rover'],
        'move_2',
        ['move_2', 1],
        'move_3',
        ['move_3', 'Synergy'],
        'move_3',
        ['move_3', 2],
        'move_4',
        'move_4',
        ['move_4', 5],
      ],
      tech: [null, null, 'Synergy', 'tech', null, 'tech', 1, 'tech', null, null, 'tech', null, 'Synergy', 2, 'tech', 5],
    },
  },
];
const CARDS_DATA = {
  1: { title: 'Temp Agency', desc: 'Advance two different trackers once each.' },
  2: { title: 'Dept of Operations', desc: 'Advance any one tracker twice.' },
  3: { title: 'Dept of Natural Resources', desc: 'Gain one biomass patch.' },
  4: { title: 'Dept of Engineering', desc: 'Gain four rover movement.' },
  5: { title: 'Salvage Yard', desc: 'Take one tile from your depot and place it. Do not advance for its resources.' },
  6: { title: 'Observance of First Planet Holiday', desc: '1 Medal' },
  7: { title: 'Rising Planet Award', desc: '2 Medals' },
  8: { title: 'First Planet Holiday', desc: '1 Medal' },
  9: { title: "People's Planet Choice Award", desc: '2 Medals' },
  10: { title: 'New Angel Investors', desc: 'Advance any three different trackers once each.' },
  11: { title: 'Wage Increase', desc: 'Advance any two different trackers once each.' },
  12: { title: 'Dept of Parks and Rec', desc: 'Gain two biomass patches.' },
  13: { title: 'Approved Overtime', desc: 'Collect two lifepods from your planet.' },
  14: { title: 'Relocation Bonus', desc: 'Teleport a rover to any grid square on the planet or tiles.' },
  15: { title: 'Top Planet Award', desc: '2 Medals' },
  16: { title: 'Depot Repair Online', desc: 'Take one tile from your depot and place it. Do not advance for its resources.' },
  17: { title: 'Landing Zone Approved', desc: 'Destroy all meteorites from one row or one column.' },
  18: { title: 'Search and Rescue Team', desc: 'Collect three lifepods from your planet.' },
  19: { title: 'Partnership Opportunity', desc: 'Advance any three different trackers once each.' },
  20: { title: 'Best in Planet Award', desc: '3 Medals' },
  21: { title: 'Unionization', desc: 'Advance all trackers to the 5th position if possible. Do not activate synergy boost.' },
  22: { title: 'Sustainable Living Act', desc: 'Your biomass patches are worth one medal each.' },
  23: { title: 'Gaming Commission', desc: '2 Medals and Advance any tracker once.' },
  24: { title: 'Planet Lottery', desc: '3 Medals and Advance any tracker once.' },
  25: { title: 'Meteor Defense Program', desc: 'Destroy any 3 meteorites.' },
  26: { title: 'Global Parks System', desc: 'Gain three biomass patches.' },
  27: { title: 'Best Planet to Live on Award', desc: '4 Medals' },
  28: { title: 'Space Citizen Decree', desc: 'Your collected lifepods are worth two medals instead of one' },
  29: { title: 'Meteorite Repo (1/4)', desc: 'Claim Meteorite repo cards to improve meteorite scoring.' },
  30: { title: 'Meteorite Repo (2/4)', desc: 'Claim Meteorite repo cards to improve meteorite scoring.' },
  31: { title: 'Meteorite Repo (3/4)', desc: 'Claim Meteorite repo cards to improve meteorite scoring.' },
  32: { title: 'Meteorite Repo (4/4)', desc: 'Claim Meteorite repo cards to improve meteorite scoring.' },
  33: { title: 'Commerce Agreement (1/4)', desc: 'Claim Commerce Agreement cards to score medals.' },
  34: { title: 'Commerce Agreement (2/4)', desc: 'Claim Commerce Agreement cards to score medals.' },
  35: { title: 'Commerce Agreement (3/4)', desc: 'Claim Commerce Agreement cards to score medals.' },
  36: { title: 'Commerce Agreement (4/4)', desc: 'Claim Commerce Agreement cards to score medals.' },
  65: {
    title: 'Have you seen the R-16? It makes the R-15 obsolete.',
    desc: 'Gain an extra Rover and position it on a tile you place this round',
  },
  66: { title: "Reserachers think they're close to a breackthrough.", desc: 'Add an extra civ card to each rank.' },
  67: { title: 'Are you up for some overtime?', desc: 'Draw an extra objective card and add it to your objectives.' },
  68: {
    title: 'Something jumped on the scanners - probably just a glitch.',
    desc: 'Advance the civ, biomass, or water tracker 3 positions. (Do not gain benefits)',
  },
  69: { title: 'More rovers or more researchers?', desc: 'Advance rover or civ tracker.' },
  70: { title: 'Check out these mods.', desc: 'Advance rover or tech tracker.' },
  71: { title: 'Can the rovers run over water?', desc: 'Advance rover or water tracker.' },
  72: { title: "Do you think we'll get stuck?", desc: 'Advance rover or biomass tracker.' },
  73: { title: "Can't anybody keep a secret?", desc: 'Advance civ or tech tracker.' },
  74: { title: 'What is the ETA on the supply shipment?', desc: 'Advance water or civ tracker.' },
  75: {
    title: "I hear it'll take 1,000 years before we have enough owygen to venture out.",
    desc: 'Advance biomass or civ tracker.',
  },
  76: { title: 'Sounds like they finally figured out hydro', desc: 'Advance tech or water tracker.' },
  77: { title: 'I heard of the experiments.', desc: 'Advance biomass or tech tracker.' },
  78: { title: 'How about that environment?', desc: 'Advance biomass or water tracker.' },
  79: { title: "I love it when there's not queue.", desc: 'Rotate the space station to any depot.' },
  80: { title: 'Just put it anywhere.', desc: 'Gain one biomass patch.' },
  81: { title: 'Wow! A special fuel canister was in the glove compartment.', desc: 'Gain a synergy boost.' },
  82: { title: 'These delivery drones are out of this world.', desc: 'Collect a lifepod from the planet.' },
  83: { title: 'Go run some analyses on this sample.', desc: 'Collect a meteorite from the planet.' },
  84: { title: "We'll take a happy accident when we get it.", desc: 'Gain a synergy boost.' },
  85: { title: 'Should we fix the flat or can it still run?', desc: 'Regress rover or civ tracker.' },
  86: { title: "What do you mean 'They cut the power?'", desc: 'Regress rover or tech tracker.' },
  87: { title: 'Try to avoid driving into the lake next time.', desc: 'Regress rover or water tracker.' },
  88: { title: "It's a rough day to survive out there.", desc: 'Regress rover or biomass tracker.' },
  89: { title: 'That airlock explosion set us back.', desc: 'Regress civ or tech tracker.' },
  90: { title: 'Rations are starting to sound delicious.', desc: 'Regress water or civ tracker.' },
  91: { title: "There's already too many people up here.", desc: 'Regress biomass or civ tracker.' },
  92: { title: 'Sounds like that hydro experiment went way south.', desc: 'Regress tech or water tracker.' },
  93: { title: "We can't keep this thing alive with extension cords.", desc: 'Regress biomass or tech tracker.' },
  94: { title: 'I thought they said the air was breathable.', desc: 'Regress biomass or water tracker.' },
  95: { title: 'I swear I just cleaned that spot.', desc: 'Add one meteorite to an empty symbol on your tiles.' },
  96: { title: 'Pick your poison today.', desc: 'Regress any single tracker if possible.' },
  97: {
    title: 'We need a clean up on row 5, I repeat, we need a clean up on row 5.',
    desc: 'Rovers cannot move onto water terrain this round.',
  },
  98: {
    title: "It's too overgrown.The rover just won't fit there.",
    desc: 'Rovers cannot move onto biomass terrain this round.',
  },
  99: { title: "It'll fry the fuel cells if we go that way.", desc: 'Rovers cannot move onto energy terrain this round.' },
  100: { title: "These aren't the vehicles you're looking for.", desc: 'Rovers cannot move onto rover terrain this round.' },
  101: {
    title: 'We lost 3 vehicles last year. They just disappeared.',
    desc: 'Rovers cannot move onto tech terrain this round.',
  },
  102: { title: "It's faster to just drive around.", desc: 'Rovers cannot move onto civ terrain this round.' },
  103: { title: 'Keep your ideas inside the box today.', desc: 'Tiles cannot be placed on the planet edge.' },
  104: { title: 'The geodesic dome must be half full.', desc: 'Do not advance one resource from your tile placement.' },
  105: { title: 'How come nothing ever works in this place?', desc: 'Regress any single tracker twice.' },
  106: { title: "This is everyone's fault but mine", desc: 'Regress any single tracker three times.' },
  107: { title: 'That thing almost clipped me!', desc: 'Add one meteorite to an empty symbol on your planet.' },
  108: { title: 'The geodesic dome is definitely half empty.', desc: 'Ignore one of the resources on your tile this round.' },
  109: {
    title: "Are you positive it's in position? Nothing happened.",
    desc: 'Do not gain milestone benefits when advancing your tracks.',
  },
  110: { title: "They just killed the project. I don't get paid enough for this!", desc: 'Destroy one of your objective cards.' },
  111: {
    title: "I don't know. One minute it was there and the next pieces were everywhere.",
    desc: 'Destroy a rover if you have more than one on your planet.',
  },
  112: {
    title: "We need more volunteers, the few of us can't do it alone.",
    desc: 'Remove one civ card from each rank at random.',
  },
  113: { title: 'It was pinging regularly and then it just stopped.', desc: 'Destroy one lifepod on your planet.' },
  114: { title: 'All that work was for nothing.', desc: 'Destroy 1 collected lifepod.' },
  115: { title: 'It just spontaneously combusted.', desc: 'Destroy 1 collected meteorite.' },
  116: {
    title: 'The entire lot is defective.',
    desc: 'Choose one shape from the current depot. Remove all tiles of that shape from the space station.',
  },
  117: { title: "I've got a bad feeling.", desc: 'Choose to gain a synergy boost or peek at the next event.' },
  118: { title: "Time is up. Let's do this.", desc: 'Choose to gain a synergy boost or peek at the next event.' },
  119: {
    title: 'Too much of any one thing is always a bad thing.',
    desc: 'Tiles cannot be placed next to a matching resource terrains.',
  },
  120: { title: "Apparently it's deeper than we thought.", desc: 'Tiles cannot be placed onto planetary ice.' },
  121: { title: 'They found some signs of life under the ice.', desc: 'Tiles cannot be placed onto planetary ice.' },
  122: { title: "They're cutting funding where now?", desc: 'Do not gain any synergy boosts this round.' },
  123: {
    title: 'These blackouts are getting more frequent.',
    desc: 'Do not gain milestone benefits when advancing your tracks.',
  },
  124: { title: 'The planete is flat. Obviously...', desc: 'Tiles cannot be placed on the planet edge.' },
};
