const PLANETS_DATA = [
  {
    id: '0',
    name: 'KSB-4156',
    desc: 'Score medals for every complete row and column.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'ice', 'land', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'ice', 'ice', 'land', 'lifepod', 'ice', 'land', 'nothing', 'nothing'],
      ['nothing', 'land', 'land', 'land', 'land', 'ice', 'land', 'land', 'ice', 'ice', 'land', 'nothing'],
      ['nothing', 'lifepod', 'land', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'lifepod', 'nothing'],
      ['ice', 'ice', 'land', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'land', 'land'],
      ['ice', 'ice', 'land', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'land', 'land'],
      ['nothing', 'land', 'lifepod', 'land', 'ice', 'ice', 'land', 'land', 'land', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'ice', 'ice', 'land', 'land', 'land', 'lifepod', 'land', 'land', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'land', 'lifepod', 'land', 'land', 'land', 'land', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'ice', 'land', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
  {
    id: '1',
    name: 'Arashi',
    desc: "Every Tile placed onto the planet's ring must also be anchored outside the ring.",
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'land', 'ice', 'ice', 'ice', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'lifepod', 'land', 'land', 'land', 'land', 'land', 'land', 'lifepod', 'nothing', 'nothing'],
      ['nothing', 'land', 'land', 'ice', 'ice', 'ice', 'land', 'ice', 'ice', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'land', 'land', 'lifepod', 'land', 'ice', 'land', 'land', 'land', 'nothing'],
      ['ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring'],
      ['ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring', 'ring'],
      ['nothing', 'ice', 'ice', 'ice', 'land', 'land', 'lifepod', 'ice', 'ice', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'land', 'ice', 'land', 'land', 'ice', 'ice', 'land', 'land', 'nothing'],
      ['nothing', 'nothing', 'lifepod', 'land', 'land', 'land', 'land', 'land', 'land', 'lifepod', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'land', 'ice', 'ice', 'ice', 'ice', 'land', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
  {
    id: '2',
    name: 'Cerberus',
    desc: 'Gain a bonus 2 medals for each planet your tiles cover completely.',
    terrains: [
      ['nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'land', 'land', 'land', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'land', 'land', 'ice', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'lifepod', 'ice', 'ice', 'ice', 'land'],
      ['nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'ice', 'ice', 'land', 'land', 'land'],
      ['nothing', 'nothing', 'land', 'land', 'land', 'nothing', 'nothing', 'ice', 'land', 'land', 'lifepod', 'nothing'],
      ['nothing', 'land', 'lifepod', 'land', 'land', 'land', 'land', 'ice', 'ice', 'ice', 'land', 'nothing'],
      ['land', 'land', 'land', 'land', 'land', 'land', 'ice', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing'],
      ['land', 'land', 'ice', 'ice', 'ice', 'ice', 'ice', 'nothing', 'land', 'land', 'ice', 'nothing'],
      ['land', 'ice', 'ice', 'land', 'land', 'ice', 'lifepod', 'land', 'land', 'land', 'ice', 'land'],
      ['land', 'ice', 'land', 'lifepod', 'land', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'land'],
      ['nothing', 'land', 'land', 'land', 'land', 'land', 'land', 'land', 'lifepod', 'land', 'ice', 'land'],
      ['nothing', 'nothing', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'land', 'land', 'land', 'nothing'],
    ],
    columnMedals: [1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1],
    rowMedals: [1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1],
  },
  {
    id: '3',
    name: 'Charybdis',
    desc: 'First tile placement must cover one of the central four squares.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'land', 'lifepod', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'ice', 'ice', 'land', 'land', 'ice', 'lifepod', 'nothing', 'nothing'],
      ['nothing', 'land', 'land', 'land', 'lifepod', 'ice', 'land', 'land', 'ice', 'ice', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'land', 'ice', 'ice', 'ice', 'ice', 'ice', 'lifepod', 'land', 'nothing'],
      ['ice', 'land', 'land', 'land', 'ice', 'hole', 'hole', 'ice', 'land', 'land', 'land', 'land'],
      ['ice', 'land', 'land', 'land', 'ice', 'hole', 'hole', 'ice', 'land', 'land', 'land', 'land'],
      ['nothing', 'land', 'land', 'land', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'ice', 'ice', 'lifepod', 'land', 'lifepod', 'ice', 'ice', 'land', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'land', 'land', 'land', 'land', 'land', 'land', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'land', 'land', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'ice',
        'ice',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
  {
    id: '4',
    name: 'Gaia',
    desc: 'Every city not covered by tiles scores two medals. Score complete rows and columns as normal.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'city',
        'lifepod',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'ice', 'land', 'land', 'land', 'land', 'ice', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'city', 'lifepod', 'ice', 'land', 'land', 'ice', 'land', 'city', 'nothing', 'nothing'],
      ['nothing', 'land', 'land', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'ice', 'lifepod', 'land', 'land', 'land', 'ice', 'land', 'land', 'nothing'],
      ['land', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'ice', 'land', 'land', 'city'],
      ['city', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'ice', 'land', 'land', 'land'],
      ['nothing', 'land', 'land', 'ice', 'land', 'land', 'land', 'lifepod', 'ice', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'lifepod', 'land', 'nothing'],
      ['nothing', 'nothing', 'city', 'land', 'land', 'land', 'land', 'land', 'land', 'city', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'land', 'land', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'lifepod',
        'city',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
  {
    id: '5',
    name: 'K-273',
    desc: 'You may not place a tile that overlaps both planet terrain and planet ice.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'ice',
        'ice',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'ice', 'ice', 'lifepod', 'ice', 'ice', 'ice', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'nothing', 'nothing'],
      ['nothing', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'land', 'lifepod', 'ice', 'ice', 'nothing'],
      ['nothing', 'ice', 'ice', 'lifepod', 'ice', 'ice', 'ice', 'ice', 'land', 'ice', 'ice', 'nothing'],
      ['ice', 'ice', 'land', 'land', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice'],
      ['ice', 'ice', 'lifepod', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'land', 'lifepod'],
      ['nothing', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'land', 'nothing'],
      ['nothing', 'ice', 'ice', 'ice', 'ice', 'land', 'land', 'ice', 'ice', 'ice', 'land', 'nothing'],
      ['nothing', 'nothing', 'ice', 'ice', 'ice', 'lifepod', 'land', 'ice', 'ice', 'ice', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'ice',
        'ice',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
  {
    id: '6',
    name: "K'Aax",
    desc: 'Your rover may not move onto toxic terrain. You may place tiles over toxic terrain to neutralize it.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'toxic', 'land', 'land', 'land', 'ice', 'ice', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'toxic', 'toxic', 'toxic', 'land', 'land', 'land', 'ice', 'lifepod', 'nothing', 'nothing'],
      ['nothing', 'ice', 'ice', 'toxic', 'lifepod', 'toxic', 'land', 'toxic', 'toxic', 'land', 'land', 'nothing'],
      ['nothing', 'ice', 'land', 'land', 'toxic', 'land', 'toxic', 'toxic', 'land', 'land', 'land', 'nothing'],
      ['lifepod', 'toxic', 'land', 'land', 'land', 'land', 'land', 'land', 'land', 'land', 'land', 'lifepod'],
      ['land', 'toxic', 'land', 'ice', 'ice', 'ice', 'land', 'land', 'ice', 'ice', 'ice', 'land'],
      ['nothing', 'land', 'ice', 'ice', 'toxic', 'ice', 'land', 'land', 'ice', 'toxic', 'toxic', 'nothing'],
      ['nothing', 'land', 'ice', 'toxic', 'ice', 'ice', 'land', 'land', 'ice', 'toxic', 'lifepod', 'nothing'],
      ['nothing', 'nothing', 'toxic', 'toxic', 'ice', 'land', 'land', 'ice', 'ice', 'toxic', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'land', 'ice', 'lifepod', 'land', 'ice', 'land', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
  {
    id: '7',
    name: 'Lacuna',
    desc: 'You may not place tiles covering the holes of the planet.',
    terrains: [
      ['nothing', 'nothing', 'nothing', 'nothing', 'land', 'ice', 'land', 'land', 'nothing', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'ice', 'ice', 'land', 'land', 'land', 'land', 'nothing', 'nothing'],
      ['nothing', 'land', 'ice', 'ice', 'land', 'nothing', 'nothing', 'land', 'land', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'ice', 'lifepod', 'nothing', 'land', 'land', 'nothing', 'land', 'land', 'land', 'nothing'],
      ['land', 'land', 'ice', 'ice', 'nothing', 'nothing', 'land', 'lifepod', 'ice', 'ice', 'ice', 'ice'],
      ['land', 'lifepod', 'land', 'ice', 'ice', 'land', 'land', 'land', 'ice', 'nothing', 'nothing', 'land'],
      ['land', 'land', 'nothing', 'land', 'ice', 'ice', 'nothing', 'land', 'ice', 'land', 'lifepod', 'land'],
      ['land', 'land', 'land', 'nothing', 'land', 'ice', 'ice', 'ice', 'ice', 'land', 'nothing', 'land'],
      ['nothing', 'land', 'land', 'nothing', 'land', 'land', 'ice', 'nothing', 'lifepod', 'land', 'land', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'land', 'lifepod', 'land', 'ice', 'land', 'land', 'nothing', 'land', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'land', 'land', 'ice', 'ice', 'land', 'land', 'land', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'nothing', 'land', 'ice', 'land', 'land', 'nothing', 'nothing', 'nothing', 'nothing'],
    ],
    columnMedals: [1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1],
    rowMedals: [1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1],
  },
  {
    id: '8',
    name: 'Oblivion',
    desc: 'Ice has amassed in the corners',
    terrains: [
      ['ice', 'ice', 'ice', 'land', 'land', 'land', 'land', 'land', 'land', 'ice', 'ice', 'ice'],
      ['ice', 'ice', 'ice', 'land', 'land', 'land', 'lifepod', 'land', 'land', 'ice', 'ice', 'ice'],
      ['ice', 'ice', 'ice', 'land', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'ice', 'ice', 'ice'],
      ['lifepod', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'lifepod', 'land', 'land'],
      ['land', 'land', 'land', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'land', 'land'],
      [
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
      ],
      [
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
      ],
      ['land', 'land', 'land', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'land', 'land'],
      ['land', 'land', 'lifepod', 'land', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'land', 'land', 'lifepod'],
      ['ice', 'ice', 'ice', 'land', 'nothing', 'nothing', 'nothing', 'nothing', 'land', 'ice', 'ice', 'ice'],
      ['ice', 'ice', 'ice', 'land', 'lifepod', 'land', 'land', 'land', 'land', 'ice', 'ice', 'ice'],
      ['ice', 'ice', 'ice', 'land', 'land', 'land', 'land', 'land', 'land', 'ice', 'ice', 'ice'],
    ],
    columnMedals: [3, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 3],
    rowMedals: [3, 3, 1, 1, 1, 0, 0, 1, 1, 1, 3, 3],
  },
  {
    id: '9',
    name: 'Pajitnov',
    desc: 'You must be able to slide your tiles into place.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'ice', 'ice', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'land', 'land', 'land', 'ice', 'ice', 'lifepod', 'nothing', 'nothing'],
      ['nothing', 'land', 'lifepod', 'ice', 'land', 'land', 'land', 'land', 'ice', 'ice', 'land', 'nothing'],
      ['nothing', 'ice', 'land', 'land', 'ice', 'ice', 'land', 'land', 'lifepod', 'land', 'land', 'nothing'],
      ['land', 'ice', 'ice', 'land', 'ice', 'ice', 'land', 'ice', 'land', 'land', 'land', 'land'],
      ['land', 'land', 'ice', 'land', 'land', 'land', 'land', 'ice', 'land', 'land', 'land', 'land'],
      ['nothing', 'land', 'lifepod', 'ice', 'land', 'land', 'land', 'ice', 'ice', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'lifepod', 'land', 'land', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'land', 'land', 'land', 'ice', 'ice', 'ice', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'ice', 'land', 'land', 'lifepod', 'land', 'ice', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
  {
    id: '10',
    name: 'Persephone',
    desc: 'Each quadrant has one restricted resource. Do not place a restricted resource in the quadrant.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'ice', 'land', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'ice', 'ice', 'ice', 'ice', 'land', 'land', 'land', 'land', 'nothing', 'nothing'],
      ['nothing', 'land', 'ice', 'land', 'lifepod', 'ice', 'land', 'land', 'land', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'ice', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'lifepod', 'nothing'],
      ['land', 'lifepod', 'ice', 'land', 'land', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice', 'ice'],
      ['land', 'land', 'ice', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'land', 'land'],
      ['nothing', 'land', 'ice', 'lifepod', 'ice', 'ice', 'land', 'land', 'land', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'ice', 'ice', 'ice', 'land', 'land', 'land', 'land', 'land', 'land', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'land', 'land', 'land', 'land', 'land', 'lifepod', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'ice', 'lifepod', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
  {
    id: '11',
    name: 'Petra',
    desc: 'You may treat the electrical currents as energy terrain. There is no Ice.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'land', 'electric', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'land',
        'lifepod',
        'electric',
        'electric',
        'land',
        'land',
        'lifepod',
        'electric',
        'nothing',
        'nothing',
      ],
      ['nothing', 'land', 'land', 'land', 'land', 'electric', 'land', 'electric', 'electric', 'electric', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'land', 'land', 'electric', 'land', 'electric', 'land', 'land', 'land', 'nothing'],
      [
        'land',
        'land',
        'electric',
        'electric',
        'electric',
        'electric',
        'land',
        'electric',
        'electric',
        'electric',
        'land',
        'land',
      ],
      ['land', 'electric', 'electric', 'land', 'lifepod', 'electric', 'land', 'electric', 'lifepod', 'electric', 'land', 'land'],
      [
        'nothing',
        'electric',
        'land',
        'land',
        'electric',
        'electric',
        'electric',
        'electric',
        'electric',
        'electric',
        'land',
        'nothing',
      ],
      ['nothing', 'electric', 'electric', 'electric', 'electric', 'land', 'land', 'electric', 'land', 'land', 'land', 'nothing'],
      [
        'nothing',
        'nothing',
        'land',
        'lifepod',
        'land',
        'land',
        'land',
        'electric',
        'electric_lifepod',
        'land',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'land', 'land', 'land', 'land', 'land', 'electric', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
  {
    id: '12',
    name: 'Tartarus',
    desc: 'Tiles may not be placed covering the chasm. Rovers may not move across the chasm with orthogonal movement.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'lifepod',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'ice', 'land', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'land', 'land', 'land', 'land', 'ice', 'ice', 'nothing', 'nothing'],
      ['nothing', 'lifepod', 'ice', 'ice', 'land', 'land', 'land', 'ice', 'ice', 'ice', 'land', 'nothing'],
      ['nothing', 'land', 'ice', 'land', 'land', 'ice', 'lifepod', 'ice', 'land', 'land', 'land', 'nothing'],
      ['land', 'ice', 'ice', 'land', 'land', 'ice', 'ice', 'ice', 'land', 'land', 'land', 'land'],
      ['ice', 'ice', 'land', 'land', 'land', 'ice', 'lifepod', 'ice', 'land', 'land', 'land', 'land'],
      ['nothing', 'land', 'land', 'land', 'land', 'land', 'land', 'ice', 'land', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'land', 'land', 'land', 'land', 'ice', 'land', 'land', 'land', 'lifepod'],
      ['nothing', 'nothing', 'land', 'land', 'land', 'land', 'lifepod', 'land', 'land', 'land', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'land', 'land', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
];
const CORPOS_DATA = [
  {
    id: '0',
    name: 'Universal Coalition',
    desc: 'Advance your trackers to gain benefits, \n    unlock milestones, and score the highest medal your tracker covers or surpasses',
    tracks: {
      civ: [null, null, 1, 'civ', null, 2, 'civ', null, 'synergy', 3, 'civ', 'synergy', null, null, 'civ', 5],
      water: [null, null, 1, 'synergy', 2, null, 3, 'synergy', 4, null, 5, null, 'synergy', 7, null, 10],
      biomass: [
        null,
        null,
        'synergy',
        'biomass',
        null,
        1,
        'biomass',
        null,
        2,
        'biomass',
        'synergy',
        'biomass',
        3,
        'biomass',
        null,
        5,
      ],
      rover: [
        null,
        'rover',
        'move_1',
        'move_1',
        'move_2',
        'move_2',
        ['move_2', 'rover'],
        'move_2',
        ['move_2', 1],
        'move_3',
        ['move_3', 'synergy'],
        'move_3',
        ['move_3', 2],
        'move_4',
        'move_4',
        ['move_4', 5],
      ],
      tech: [null, null, 'synergy', 'tech', null, 'tech', 1, 'tech', null, null, 'tech', null, 'synergy', 2, 'tech', 5],
    },
  },
  {
    id: '1',
    name: 'Cosmos inc',
    desc: 'Choose to position a collected lifepod onto your advancement track or onto your scoring area. Your trackers skip over lifepods when advancing. Benefits and medals covered by lifepods are ignored.',
    tracks: {
      civ: [null, null, 1, 'civ', null, 2, 'civ', null, 'synergy', 3, 'civ', 'synergy', null, null, 'civ', 5],
      water: [null, null, 1, 'synergy', 2, null, 3, 'synergy', 4, null, 5, null, 'synergy', 7, null, 10],
      biomass: [
        null,
        null,
        'synergy',
        'biomass',
        null,
        1,
        'biomass',
        null,
        2,
        'biomass',
        'synergy',
        'biomass',
        3,
        'biomass',
        null,
        5,
      ],
      rover: [
        null,
        'rover',
        'move_1',
        'move_1',
        'move_2',
        'move_2',
        'move_2',
        'move_2',
        ['move_2', 1],
        'move_2',
        ['move_2', 'synergy'],
        'move_2',
        ['move_2', 2],
        'move_3',
        'move_3',
        ['move_3', 5],
      ],
      tech: [null, null, 'synergy', 'tech', null, 'tech', 1, 'tech', null, null, 'tech', null, 'synergy', 2, 'tech', 5],
    },
  },
  {
    id: '2',
    name: 'Flux Industries',
    desc: 'Your flux token designates on of your resource tracks as the flux track. Whenever you unlock a tech, you may reposition your flux token. Only your most recently unlocked teck is available.',
    tracks: {
      civ: [null, null, 1, 'civ', null, 2, 'civ', null, 'synergy', 3, 'civ', 'synergy', null, null, 'civ', 5],
      water: [null, null, 1, 'synergy', 2, null, 3, 'synergy', 4, null, 5, null, 'synergy', 7, null, 10],
      biomass: [
        null,
        null,
        'synergy',
        'biomass',
        null,
        1,
        'biomass',
        null,
        2,
        'biomass',
        'synergy',
        'biomass',
        3,
        'biomass',
        null,
        5,
      ],
      rover: [
        null,
        'rover',
        'move_1',
        'move_1',
        'move_2',
        'move_2',
        ['move_2', 'rover'],
        'move_2',
        ['move_2', 1],
        'move_2',
        ['move_2', 'synergy'],
        'move_2',
        ['move_2', 2],
        'move_3',
        'move_3',
        ['move_3', 5],
      ],
      tech: [null, null, 'synergy', 'tech', null, 'tech', 1, 'tech', null, null, 'tech', null, 'synergy', 2, 'tech', 5],
    },
  },
  {
    id: '3',
    name: 'Horizon Group',
    desc: 'To Collect meteorite, your rover must pick it up and deliver it to a rover resource on your planet.',
    tracks: {
      civ: [null, null, 1, 'civ', null, 2, 'civ', null, 'synergy', 3, 'civ', 'synergy', null, null, 'civ', 5],
      water: [null, null, 1, 'synergy', 2, null, 3, 'synergy', 4, null, 5, null, 'synergy', 7, null, 10],
      biomass: [
        null,
        null,
        'synergy',
        'biomass',
        null,
        1,
        'biomass',
        null,
        2,
        'biomass',
        'synergy',
        'biomass',
        3,
        'biomass',
        null,
        5,
      ],
      rover: [
        null,
        'rover',
        'move_2',
        ['move_2', 'rover'],
        'move_2',
        'move_3',
        ['move_3', 'rover'],
        'move_3',
        ['move_4', 1],
        ['move_4', 'rover'],
        ['move_4', 'synergy'],
        'move_4',
        ['move_5', 2],
        'move_5',
        'move_5',
        ['move_5', 5],
      ],
      tech: [null, null, 'synergy', 'tech', null, 'tech', 1, 'tech', null, null, 'tech', null, 'synergy', 2, 'tech', 5],
    },
  },
  {
    id: '4',
    name: 'Jump Drive',
    desc: 'Choose to place a collected lifepod onto your tech or your scoring area. A lifepod placed onto tech unlocks the tech in any order.',
    tracks: {
      civ: [null, null, 1, 'civ', null, 2, 'civ', null, 'synergy', 3, 'civ', 'synergy', null, null, 'civ', 5],
      water: [null, null, 1, 'synergy', 2, null, 3, 'synergy', 4, null, 5, null, 'synergy', 7, null, 10],
      biomass: [
        null,
        null,
        'synergy',
        'biomass',
        null,
        1,
        'biomass',
        null,
        2,
        'biomass',
        'synergy',
        'biomass',
        3,
        'biomass',
        null,
        5,
      ],
      rover: [
        null,
        'rover',
        'move_1',
        'move_1',
        'move_2',
        'move_2',
        'move_2',
        'move_2',
        ['move_2', 1],
        'move_2',
        ['move_2', 'synergy'],
        'move_2',
        ['move_2', 2],
        'move_3',
        'move_3',
        ['move_3', 5],
      ],
      tech: [null, 5, 'synergy', null, null, null, 3, null, 2, null, null, 1, 'synergy', null, null, null],
    },
  },
  {
    id: '5',
    name: 'Make Shift',
    desc: 'You may advance any tracker diagonally onto an adjacent track. Any tracker may claim any benefit. Tech Levels are locked if no tracker is currently unlocking the tech.',
    tracks: {
      civ: [null, null, 1, 'civ', null, 2, 'civ', null, 'synergy', 3, 'civ', 'synergy', null, null, 'civ', 5],
      water: [null, null, 1, 'synergy', 2, null, 'synergy', 3, 'synergy', null, null, 4, 'synergy', null, null, 5],
      biomass: [
        null,
        null,
        'synergy',
        'biomass',
        null,
        1,
        'biomass',
        null,
        2,
        'biomass',
        'synergy',
        'biomass',
        3,
        'biomass',
        null,
        5,
      ],
      rover: [
        null,
        'rover',
        'move_1',
        'move_1',
        'move_2',
        'move_2',
        ['move_2', 'rover'],
        'move_2',
        ['move_2', 'synergy'],
        'move_2',
        ['move_2', 1],
        'move_2',
        ['move_2', 2],
        'move_3',
        'move_3',
        ['move_3', 5],
      ],
      tech: [null, null, 'synergy', 'tech', null, 'tech', 1, 'tech', null, null, 'tech', null, 'synergy', 2, 'tech', 5],
    },
  },
  {
    id: '6',
    name: 'Oasis Ultd.',
    desc: 'Advance your water tracker once for each water terrain square that covers planet ice. Gain the benefits from advancing your water tracker even when it advances onto another track.',
    tracks: {
      civ: [null, null, 1, 'civ', null, 2, 'civ', null, 'synergy', 3, 'civ', 'synergy', null, null, 'civ', 5],
      water: [null, null, 'skip', 'synergy', 'skip', 'synergy', 3, 'skip', 'skip', 5, 'skip', 8, 'skip', 12, null, 15],
      biomass: [
        null,
        null,
        'synergy',
        'biomass',
        null,
        1,
        'biomass',
        null,
        2,
        'biomass',
        'synergy',
        'biomass',
        3,
        'biomass',
        null,
        5,
      ],
      rover: [
        null,
        'rover',
        'move_1',
        'move_1',
        'move_2',
        'move_2',
        ['move_2', 'rover'],
        'move_2',
        ['move_2', 1],
        'move_2',
        ['move_2', 'synergy'],
        'move_2',
        ['move_2', 2],
        'move_3',
        'move_3',
        ['move_3', 5],
      ],
      tech: [null, null, 'synergy', 'tech', null, 'tech', 1, 'tech', null, null, 'tech', null, 'synergy', 2, 'tech', 5],
    },
  },
  {
    id: '7',
    name: 'Republic',
    desc: 'You must regress another tracker each time you claim a milestone from the civ track. Do not claim benefits from regressing.',
    tracks: {
      civ: [null, null, 'civ', null, 'civ', null, 'civ', null, 'civ', null, 'civ', null, 'civ', null, 'civ', 5],
      water: [null, null, 1, 'synergy', 2, null, 3, 'synergy', 4, null, 5, null, 'synergy', 7, null, 10],
      biomass: [
        null,
        null,
        'synergy',
        'biomass',
        null,
        1,
        'biomass',
        null,
        2,
        'biomass',
        'synergy',
        'biomass',
        3,
        'biomass',
        null,
        5,
      ],
      rover: [
        null,
        'rover',
        'move_1',
        'move_1',
        'move_2',
        'move_2',
        'move_2',
        'move_2',
        ['move_2', 1],
        'move_2',
        ['move_2', 'synergy'],
        'move_2',
        ['move_2', 2],
        'move_3',
        'move_3',
        ['move_3', 5],
      ],
      tech: [null, null, 'synergy', 'tech', null, 'tech', 1, 'tech', null, null, 'tech', null, 'synergy', 2, 'tech', 5],
    },
  },
  {
    id: '8',
    name: 'Wormhole Corp',
    desc: 'Advance your biomass tracker from tile placement only when you expand a biomass terrain area.',
    tracks: {
      civ: [null, null, 1, 'civ', null, 2, 'civ', null, 'synergy', 3, 'civ', 'synergy', null, null, 'civ', 5],
      water: [null, null, 1, 'synergy', 2, null, 3, 'synergy', 4, null, 5, null, 'synergy', 7, null, 10],
      biomass: [
        null,
        'skip',
        'synergy',
        'biomass',
        ['skip', 1],
        'synergy_civ',
        'biomass',
        ['skip', 2],
        'synergy_water',
        'biomass',
        ['skip', 3],
        'synergy_tech',
        'biomass',
        ['skip', 5],
        'synergy_rover',
        'biomass',
      ],
      rover: [
        null,
        'rover',
        'move_1',
        'move_1',
        'move_2',
        'move_2',
        ['move_2', 'rover'],
        'move_2',
        ['move_2', 1],
        'move_3',
        ['move_3', 'synergy'],
        'move_3',
        ['move_3', 2],
        'move_4',
        'move_4',
        ['move_4', 5],
      ],
      tech: [null, null, 'synergy', 'tech', null, 'tech', 1, 'tech', null, null, 'tech', null, 'synergy', 2, 'tech', 5],
    },
  },
];
