const PLANETS_DATA = [
  {
    id: '0',
    name: 'KSB-4156',
    desc: 'Score medals for every complete row and column.',
    terrains: [
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
      ['nothing', 'nothing', 'nothing', 'ice', 'land', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'ice', 'ice', 'land', 'lifepod', 'ice', 'land', 'nothing', 'nothing'],
      ['nothing', 'land', 'land', 'land', 'land', 'ice', 'land', 'land', 'ice', 'ice', 'land', 'nothing'],
      ['nothing', 'lifepod', 'land', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'lifepod', 'nothing'],
      ['ice', 'ice', 'land', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'land', 'land'],
      ['ice', 'ice', 'land', 'land', 'land', 'ice', 'land', 'land', 'land', 'land', 'land', 'land'],
      ['nothing', 'land', 'lifepod', 'land', 'ice', 'ice', 'land', 'land', 'land', 'land', 'land', 'nothing'],
      ['nothing', 'land', 'land', 'ice', 'ice', 'land', 'land', 'land', 'lifepod', 'land', 'land', 'nothing'],
      ['nothing', 'nothing', 'land', 'ice', 'land', 'lifepod', 'land', 'land', 'land', 'land', 'nothing', 'nothing'],
      ['nothing', 'nothing', 'nothing', 'ice', 'land', 'land', 'land', 'land', 'land', 'nothing', 'nothing', 'nothing'],
      [
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'land',
        'land',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
        'nothing',
      ],
    ],
    columnMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
    rowMedals: [1, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 1],
  },
];
